优化排版，增加手动安装 Mod 加载器内容
LTCatt/PCL2Help pull request #104
Opened 2021-09-13 04:11 UTC by tjw123hh

2021-09-13 04:12 UTC, tjw123hh commented
ok

2021-09-13 12:02 UTC, LTCatt requested changes

2021-09-13 12:02 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.xaml
> +<local:MyCard Title="手动安装 Mod 加载器" CanSwap="True" IsSwaped="True">
安装步骤建议使用网络中的已有教程，仅说明如何从 PCL2 下载手动安装包即可。

2021-09-18 08:55 UTC, tjw123hh commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.xaml
> +<local:MyCard Title="手动安装 Mod 加载器" CanSwap="True" IsSwaped="True">
无法找到合适教程

2021-09-18 08:57 UTC, tjw123hh commented
ok

2021-09-27 01:35 UTC, LTCatt requested changes

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +<local:MyCard Title="下载并安装 Mod （CurseForge）" Margin="0,0,0,15" CanSwap="True" IsSwaped="True">
使用原本样式。空格加中文括号间距太大了……

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +<local:MyHint Margin="0,0,0,15" Text="该帮助页面中“模组”均称为“Mod（s）”"/>
无需此提示。

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod.json
> +	"__author__": "Big_Cake、Logic_530、WTP016、tjw123hh",
未修改 json 文件则不写入 author，因此请使用原始内容。

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod.json
> +	"Description": "下载、导入 Minecraft Mod",
在这里添加 “模组” 是为了让这条能被搜索，请使用原始内容。

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 LiteLoader.json
> +	"__author__": "Big_Cake、Logic_530、WTP016、tjw123hh",
请根据该 json 文件的实际作者写入 author。

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.json
> +	"Description": "使用 PCL2 安装功能安装 Fabric",
建议改为 “使用 PCL2 自动或手动安装 Fabric”，其他文件同理。

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.xaml
> +        <TextBlock TextWrapping="Wrap" LineHeight="17" Text="PCL2 自带了自动安装功能，可以更加方便地安装 Mod 加载器。"/>
删掉（

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.xaml
> +                    Text="2. 选择适合的 Fabric 版本以及 Fabric API，建议安装稳定版/推荐版，出现错误可以尝试最新版" Grid.Row="0" Grid.Column="0"/>
Fabric 无需考虑稳定版，理论上直接选最新就行，因此无需刻意描述这部分

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.xaml
> +        <local:MyHint Margin="0,0,0,15" Text="请先下载对应版本的原版 Minecraft 作为前置版本"/>
使用文本而非 MyHint

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.xaml
> +               Text="6. 按照“安装 Mod（模组）”中的“下载并安装 Mod （内置）”里的方法安装 Fabric API。"/>
添加一个 MyListItem 直接指向该帮助

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.xaml
> +        <TextBlock TextWrapping="Wrap" LineHeight="17" Text="PCL2 自带了自动安装功能，可以更加方便地安装 Mod 加载器。"/>
其他文件也是（

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.xaml
> +                    Text="2. 选择适合的 Fabric 版本以及 Fabric API，建议安装稳定版/推荐版，出现错误可以尝试最新版" Grid.Row="0" Grid.Column="0"/>
其他文件也是（

2021-09-27 01:35 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Fabric.xaml
> +        <local:MyHint Margin="0,0,0,15" Text="请先下载对应版本的原版 Minecraft 作为前置版本"/>
其他文件也是（

2021-09-27 11:59 UTC, Logic530 commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Forge.xaml
> +                Text="打开 .minecraft 文件夹" EventType="打开文件" EventData="{path}/.minecraft"/>
安装到未隔离的.minecraft路径是否会导致问题？

2021-09-27 12:03 UTC, Logic530 commented on Minecraft/安装 Mod.xaml
> +        <TextBlock TextWrapping="Wrap" Margin="0,0,0,4" LineHeight="17" Text="Mod 加载器是 Minecraft 安装 Mod 的必要前置条件，要想安装 Mod 必须先安装 Mod 加载器， PCL2 目前支持自动安装 Forge，Fabric，LiteLoader 三种 Mod 加载器，其中 Forge 与 Fab
原文的此段的中心是分析在现代版本中如何选择加载器，不需要介绍PCL的自动安装功能

2021-09-27 12:05 UTC, Logic530 commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 LiteLoader.xaml
> +            <Image Margin="250,0,0,0" HorizontalAlignment="Right" Source="https://cdn.jsdelivr.net/gh/tjw123hh/imgs@main/PCL2Help-1.png"/>
图片顺序错误

2021-09-27 12:22 UTC, Logic530 commented
对于这篇帮助，我认为其主要目的是帮助没有使用过Mod的玩家快速上手使用Mod，故整体帮助应该尽量从简。PCL的自动安装功能已经足够简单易用，不需要逐个图片介绍应该点击什么按钮。并且自动安装鲜有出错，手动安装方法应该省略或另开页面。对于LiteLoader的不做介绍是有合理性的，因为其已经弃用多时并且没有任何不可替代的优质Mod。
另一方面，作为较正式的说明页面，应该避免使用任何经过自定义的PCL截图（标题、背景、或是主题），以避免产生误导。

2021-09-27 13:11 UTC, LTCatt commented on Minecraft/安装 Mod 加载器/安装 Mod 加载器 Forge.xaml
> +                Text="打开 .minecraft 文件夹" EventType="打开文件" EventData="{path}/.minecraft"/>
不会，它会新建一个版本文件夹，这才是正确的做法

2021-09-27 13:13 UTC, LTCatt commented
考虑到大多数改动实质上并不需要，我个人决定采用 #110 替代这个 PR，抱歉（

2021-09-27 13:13 UTC, closed without merging