更新一些玩意
LTCatt/PCL2Help pull request #114
Opened 2021-09-28 22:33 UTC by BoxuanZng

2021-09-29 04:28 UTC, WTP016-CN requested changes

2021-10-02 16:20 UTC, WTP016-CN requested changes

2021-10-02 16:20 UTC, WTP016-CN commented on 启动器/联机.xaml
> +                   Text="复制MOD名称(3)" EventType="复制文本" EventData="mcwifipnp" />
复制 Mod 名称 (3)
请按照帮助库编写规范编写

2021-10-02 16:20 UTC, WTP016-CN commented on 帮助/提交帮助 - Sublime Text.xaml
> +		                Text="注意：Subl本身并不支持git提交和拉取，请使用Sublime Merger以及git命令配合Subl"/>
Sublime Merger前后空格
请参考帮助库编写规范

2021-10-02 16:20 UTC, WTP016-CN commented on 帮助/提交帮助 - Sublime Text.xaml
> +                    Text="2. 用Git命令拉取存储库"/>
同上

2021-11-20 14:16 UTC, LTCatt requested changes
请先解决上面 WTP 说的问题……

2021-11-27 11:12 UTC, WTP016-CN requested changes

2021-11-27 11:12 UTC, WTP016-CN commented on 帮助/提交帮助 - Sublime Text.xaml
> +        <TextBlock Margin="0,0,0,4" LineHeight="17" Text="Sublime Text(下文使用该软件的简称 Subl)，是一款由Sublime HQ Pty公司开发的跨平台编辑器。你可以通过下面的按钮获取 Sublime Text 的 Windows 版本。" />
是一款跨平台文本编辑器。
不需要过长的简介

2021-11-27 11:12 UTC, WTP016-CN commented on 帮助/提交帮助 - Sublime Text.xaml
> +            <local:MyButton MinWidth="140" Padding="13,0" Margin="0,0,20,0" HorizontalAlignment="Left" ColorType="Highlight"
可以在此处加上：
<local:MyHint Margin="0,0,0,15" Text="Subl 是付费软件，仅提供 15 天使用，后续需要付费使用。" />

2021-12-22 13:29 UTC, LTCatt commented
由于太久没有更改，再等会不动就关了……

2022-01-03 02:13 UTC, closed without merging