改了外观类的一些东西
LTCatt/PCL2Help pull request #115
Opened 2021-09-29 07:02 UTC by WTP016-CN

在部分帮助的文本后加上了句号 部分教程的全角箭头改为半角 更改了部分帮助文件的名称

2021-11-20 13:39 UTC, LTCatt requested changes

2021-11-20 13:39 UTC, LTCatt commented on 个性化/XAML 格式.xaml
> +                   Text="下载本篇的代码" EventType="下载文件" EventData="http://cdn.jsdelivr.net/gh/LTCatt/PCL2Help@master/%E4%B8%AA%E6%80%A7%E5%8C%96/XAML%20%E6%A0%BC%E5%BC%8F.xaml" ToolTip="下载本篇的代码" />
不指向 GitHub 的话会导致文件可能不是最新，不推荐修改

2021-11-20 13:39 UTC, LTCatt commented on 指南/资源安装指南.xaml
> +<local:MyCard Title="安装资源包" CanSwap="True" IsSwaped="True">
“材质包” 是老版本 MC 的称呼，建议保留

2021-11-20 13:39 UTC, LTCatt commented
此外，最好再全局搜索一下有没有其他帮助页面引用了被你重命名的页面（

2021-11-20 14:24 UTC, WTP016-CN commented on 个性化/XAML 格式.xaml
> +                   Text="下载本篇的代码" EventType="下载文件" EventData="http://cdn.jsdelivr.net/gh/LTCatt/PCL2Help@master/%E4%B8%AA%E6%80%A7%E5%8C%96/XAML%20%E6%A0%BC%E5%BC%8F.xaml" ToolTip="下载本篇的代码" />
我更改的原因是 jsdelivr 几乎是瞬间更新 如果有延迟也会 <24h 且 jsdelivr 在国内有机器可以下载 所以才更改为 jsdelivr

2021-11-27 13:41 UTC, LTCatt commented
还有个合并冲突（

2021-12-18 03:23 UTC, WTP016-CN commented
我这边由于无法访问 Github 所以不能使用命令行解决冲突- -
我是使用 Coding 镜像推东西的- -

2021-12-18 04:57 UTC, closed without merging

2021-12-18 04:59 UTC, WTP016-CN commented
由于一些问题 重新发pr - - 等我修好问题先- -