补充了一下联机的帮助
LTCatt/PCL2Help pull request #121
Opened 2021-12-20 11:58 UTC by bwtx2021

2021-12-20 12:21 UTC, WTP016-CN requested changes

2021-12-20 12:21 UTC, WTP016-CN commented on Minecraft/整合包安装.xaml
> +                   Text="整合包(Modpack, Modification Packages)是包含已经配置好的、可能包含剧情的、包含 Mod 的 Minecraft 游戏整合文件。&#xa;目前国内用户能够接触到的整合包文件一共有三种：包含启动器的整合包；使用 MCBBS 格式的整合包；使用 CurseForge 托管的整合包。&#xa;这三种整合包的安装方式不相同。
包含启动器这一类包含了MCBBS格式整合包(?

2021-12-21 10:19 UTC, bwtx2021 commented on Minecraft/整合包安装.xaml
> +                   Text="整合包(Modpack, Modification Packages)是包含已经配置好的、可能包含剧情的、包含 Mod 的 Minecraft 游戏整合文件。&#xa;目前国内用户能够接触到的整合包文件一共有三种：包含启动器的整合包；使用 MCBBS 格式的整合包；使用 CurseForge 托管的整合包。&#xa;这三种整合包的安装方式不相同。
然而并不是的，没了解过MCBBS整合包规范吗？

2021-12-21 10:19 UTC, bwtx2021 commented on Minecraft/整合包安装.xaml
> +                   Text="整合包(Modpack, Modification Packages)是包含已经配置好的、可能包含剧情的、包含 Mod 的 Minecraft 游戏整合文件。&#xa;目前国内用户能够接触到的整合包文件一共有三种：包含启动器的整合包；使用 MCBBS 格式的整合包；使用 CurseForge 托管的整合包。&#xa;这三种整合包的安装方式不相同。
> 包含启动器这一类包含了MCBBS格式整合包(?

https://www.mcbbs.net/forum.php?mod=viewthread&tid=1247765&mobile=2

2021-12-21 10:49 UTC, WTP016-CN commented on Minecraft/整合包安装.xaml
> +                   Text="整合包(Modpack, Modification Packages)是包含已经配置好的、可能包含剧情的、包含 Mod 的 Minecraft 游戏整合文件。&#xa;目前国内用户能够接触到的整合包文件一共有三种：包含启动器的整合包；使用 MCBBS 格式的整合包；使用 CurseForge 托管的整合包。&#xa;这三种整合包的安装方式不相同。
对不起 真的不知道- -

2021-12-22 13:28 UTC, LTCatt reviewed
之后联机部分还要改，等到改完了再说吧……

2021-12-22 13:28 UTC, LTCatt commented on 启动器/联机.xaml
> +                   Text="网络状态评级主要分为以下几种：&#xa; S+ ：你的网络状态良好，并且拥有独立的公网 IP ，可以与他人低延迟联机。&#xa; S ：你的网络状态良好， NAT 环境为完全圆锥（ FullCone ），可以与他人低延迟联机。&#xa; C ：你的网络状态较差， NAT 环境为端口受限圆锥（ PortRestrictedCone ），联机延迟可能
不是，哪来的 S+，我都不知道

2021-12-22 13:28 UTC, closed without merging

2021-12-22 23:55 UTC, bwtx2021 commented
那你公网开放咋写的


在 2021年12月22日，下午9:28，龙腾猫跃 ***@***.***> 写道：

﻿

@LTCatt commented on this pull request.

之后联机部分还要改，等到改完了再说吧……

________________________________

In 启动器/联机.xaml<https://github.com/LTCatt/PCL2Help/pull/121#discussion_r773886595>:

> @@ -46,4 +46,18 @@
     </StackPanel>
 </local:MyCard>

-<local:MyHint Margin="0,0,0,15" Text="作者：龙腾猫跃、猫猫" IsWarn="False" />
+<local:MyCard Title="联机界面左上角的网络状态评级是什么意思？" CanSwap="True" IsSwaped="True">
+    <StackPanel Margin="25,40,23,11">
+           <TextBlock Margin="0,0,0,4" LineHeight="17"
+                   Text="网络状态评级主要分为以下几种：&#xa; S+ ：你的网络状态良好，并且拥有独立的公网 IP ，可以与他人低延迟联机。&#xa; S ：你的网络状态良好， NAT 环境为完全圆锥（ FullCone ），可以与他人低延迟联机。&#xa; C ：你的网络状态较差， NAT 环境为端口受限圆锥（ PortRestrictedCone ），联机延迟可能较高。&#xa; D ：你的网络状态较差， NAT 环境为对称（ Symmetric ），联机延迟可能较高，并且有很大概率无法连接。&#xa; F ：你的网络状态极差， PCL2 检测到你的网络禁止了 Minecraft 局域网房间广播所使用的 UDP 包，有可能无法使用联机功能。&#xa;？： PCL2 检测不到你的 NAT ，或 NAT 类型未知。若需要，建议使用专业的 NAT 检测工具手动检测。" />


不是，哪来的 S+，我都不知道

—
Reply to this email directly, view it on GitHub<https://github.com/LTCatt/PCL2Help/pull/121#pullrequestreview-838455762>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOM5WL727PFR4AX67JQSQQ3USHG7VANCNFSM5KNQSN7A>.
You are receiving this because you authored the thread.Message ID: ***@***.***>