更新过时的 Iris Shader 的相关信息
LTCatt/PCL2Help pull request #123
Opened 2022-01-09 03:22 UTC by Wudji

2022-01-20 07:53 UTC, Big-Cake-jpg requested changes
Iris Shader 和 Minecraft 还会持续更新
所以这里推荐把 `1.18.1` 改为 `以上`
如果不改的话，以后每次 Iris Shader 出针对新版 Minecraft 的新版本的话又得继续改

2022-01-27 12:56 UTC, WTP016-CN requested changes

2022-01-27 12:56 UTC, WTP016-CN commented on Minecraft/安装光影.xaml
> +                   Text="目前提供光影功能的 Mod 有 OptiFine 和 Iris Shaders，前者支持 Forge 加载器（可以通过 OptiFabric Mod 兼容 Fabric）而后者支持 Fabric 加载器。OptiFine 几乎支持所有的 Minecraft 版本而 Iris Shaders 作为新兴的光影 Mod，目前支持的游戏版本为1.16.5
改完之后应该是这样子的:
目前提供光影功能的 Mod 有 OptiFine 和 Iris Shaders，前者支持 Forge 加载器（可以通过 OptiFabric Mod 兼容 Fabric）而后者支持 Fabric 加载器。OptiFine 几乎支持所有的 Minecraft 版本而 Iris Shaders 作为新兴的光影 Mod，目前支持的游戏版本为 1.16.5 及以上版本。一般情况下，OptiFine 是使用光影的最佳选择。

2022-01-28 09:02 UTC, Big-Cake-jpg requested changes
还得改一下

2022-01-28 09:02 UTC, Big-Cake-jpg commented on Minecraft/安装光影.xaml
> +                   Text="OptiFine 可以通过安装 OptiFabric Mod 兼容 Fabric 加载器。关于安装 OptiFabric 的详细说明，请查看请查看帮助“安装 Mod”。" />
OptiFine 可以通过安装 OptiFabric Mod 兼容 Fabric 加载器。关于安装 OptiFabric 的详细说明，请查看帮助 “安装 Mod” 。

> 后边再加上个帮助跳转链接，详见 “XAML 格式” 帮助

2022-02-02 14:46 UTC, LTCatt requested changes

2022-02-02 14:46 UTC, LTCatt commented on Minecraft/安装光影.xaml
> +        <Image HorizontalAlignment="Center" Source="https://attachment.mcbbs.net/data/myattachment/forum/202201/27/210719rqouu2cogeur5qzl.png" />
不建议使用 MCBBS 作为图床

2022-02-03 14:01 UTC, jiadanjun commented
[crash-2022-02-03_21.29.37-client.txt](https://github.com/LTCatt/PCL2Help/files/7995129/crash-2022-02-03_21.29.37-client.txt)
[debug.log](https://github.com/LTCatt/PCL2Help/files/7995130/debug.log)
[latest.log](https://github.com/LTCatt/PCL2Help/files/7995131/latest.log)
[PCL2 启动器日志.txt](https://github.com/LTCatt/PCL2Help/files/7995133/PCL2.txt)
[游戏崩溃前的输出.txt](https://github.com/LTCatt/PCL2Help/files/7995134/default.txt)
大家能帮我看看吗?

2022-02-03 14:05 UTC, Wudji commented
> [crash-2022-02-03_21.29.37-client.txt](https://github.com/LTCatt/PCL2Help/files/7995129/crash-2022-02-03_21.29.37-client.txt) [debug.log](https://github.com/LTCatt/PCL2Help/files/7995130/debug.log) [latest.log](https://github.com/LTCatt/PCL2Help/files/7995131/latest.log) [PCL2 启动器日志.txt](https://github.com/LTCatt/PCL2Help/files/7995133/PCL2.txt) [游戏崩溃前的输出.txt](https://github.com/LTCatt/PCL2Help/files/7995134/default.txt) 大家能帮我看看吗?

已经确认了从昨天晚上开始，使用非正版玩家的皮肤离线登录进入 Forge 版的存档时导致游戏崩溃。
如果遇到了这个情况，并且现在真的很急着想进游戏的话，可以在 “设置 → 游戏 → 离线皮肤” 中选择 “正版皮肤”，并输入随便一个你知道的正版玩家名（例如 LTCat），即可正常进入存档，但这样有可能会导致物品栏里的东西丢失。不急的话可以先等等……
该 Bug 目前正在紧急修复中，在确定修复方法后我会立即更新

修好了修好了，妈耶。今晚发一个紧急更新。
原因是 Forge 进行了 UUID 格式校验，因此本次更新会导致 使用离线登录且未使用正版皮肤 的玩家的 UUID 改变，这可能会导致物品栏里的物品丢失，抱歉，这个真的没办法……[跪了]……
什么玄学。

2022-02-03 14:09 UTC, LTCatt approved these changes

2022-02-03 14:09 UTC, merged