添加了对EventType为打开帮助的介绍以及对local:MyListItem的简介
LTCatt/PCL2Help pull request #129
Opened 2022-04-05 07:38 UTC by Tu-Chenjia

添加了对EventType为打开帮助的介绍以及对local:MyListItem的简介

2022-04-05 08:28 UTC, WTP016-CN requested changes

2022-04-05 08:28 UTC, WTP016-CN commented on 个性化/XAML 格式.xaml
> +                   Text="其中，Logo指的是列表项目的图标，所指定的可以是链接也可以是文件路径，Title则是列表项的大标题，Info指详细信息，它将会以灰色显示在大标题下方,Type必不可少，只有在Type属性里输入Clickable才能够被触发。"/>
其中，Logo 指的是列表项目的图标，所指定的可以是链接也可以是文件路径，Title 则是列表项的大标题，Info 指详细信息，它将会以灰色显示在大标题下方, Type 必不可少，只有在 Type 属性里输入 Clickable 才能够被触发。

2022-04-05 08:28 UTC, WTP016-CN commented on 个性化/XAML 格式.xaml
> +                   Text="在需要更详细的列出内容时，你可以使用列表项(local:MyListItem)来替代按钮。在列表项中，点击操作的使用方式与按钮相同。" />
在需要更详细的列出内容时，你可以使用列表项“local:MyListItem”来替代按钮。在列表项中，点击操作的使用方式与按钮相同。

2022-04-05 08:57 UTC, Tu-Chenjia commented on 个性化/XAML 格式.xaml
> +                   Text="其中，Logo指的是列表项目的图标，所指定的可以是链接也可以是文件路径，Title则是列表项的大标题，Info指详细信息，它将会以灰色显示在大标题下方,Type必不可少，只有在Type属性里输入Clickable才能够被触发。"/>
谢谢，正在修改

2022-04-05 08:57 UTC, Tu-Chenjia commented on 个性化/XAML 格式.xaml
> +                   Text="在需要更详细的列出内容时，你可以使用列表项(local:MyListItem)来替代按钮。在列表项中，点击操作的使用方式与按钮相同。" />
谢谢，正在修改

2022-04-05 08:58 UTC, WTP016-CN commented on 个性化/XAML 格式.xaml
> +                   Text="在需要更详细的列出内容时，你可以使用列表项(local:MyListItem)来替代按钮。在列表项中，点击操作的使用方式与按钮相同。" />
> 谢谢，正在修改

其实不用回的(

2022-04-06 01:09 UTC, Tu-Chenjia commented
在哪里Code Review

2022-04-07 07:02 UTC, LTCatt requested changes

2022-04-07 07:02 UTC, LTCatt commented on 个性化/XAML 格式.xaml
> +                   Text="其中，Logo 指的是列表项目的图标，所指定的可以是链接也可以是文件路径，Title 则是列表项的大标题，Info 指详细信息，它将会以灰色显示在大标题下方, Type 必不可少，只有在 Type 属性里输入 Clickable 才能够被触发。"/>
Type 不输入 Clickable 时它也可以用于单纯展示信息；Info 也是可选的

2022-04-07 07:02 UTC, LTCatt commented on 个性化/XAML 格式.xaml
> +<!--我的更改-->
删除此行。

2022-04-07 07:02 UTC, LTCatt commented on 个性化/XAML 格式.xaml
> +                   Text="EventType 为打开帮助，在 EventData 中输入（帮助所在的卡片）/（帮助文件名.json）后即可通过点击按钮来快速打开帮助页面。"/>
EventData 实际上是它在帮助库中的文件路径，不要使用 “帮助所在的卡片” 这种描述

2022-05-20 17:25 UTC, LTCatt approved these changes

2022-05-20 17:25 UTC, merged