Update 提交帮助 - VSCode.xaml
LTCatt/PCL2Help pull request #164
Opened 2022-06-11 03:33 UTC by zkitefly

2022-06-22 03:32 UTC, LTCatt requested changes

2022-06-22 03:32 UTC, LTCatt commented on 帮助/提交帮助 - VSCode.xaml
> +                            Text="点击下载 VSCode（若下载慢，可使用PCL2中的“更多”->“百宝箱”->“下载自定义文件”来下载" EventType="打开网页" EventData="https://code.visualstudio.com/docs/?dv=win" />
别在一个按钮里塞这么多字啊（

2022-06-25 11:33 UTC, Big-Cake-jpg commented
似乎直接从 VSCode 官网提供的下载链接下载速度非常慢

而且 PCL2 自定义下载使用上述链接下载到的文件没有后缀名

2022-07-08 03:15 UTC, zkitefly commented on 帮助/提交帮助 - VSCode.xaml
> +                            Text="点击下载 VSCode（若下载慢，可使用PCL2中的“更多”->“百宝箱”->“下载自定义文件”来下载" EventType="打开网页" EventData="https://code.visualstudio.com/docs/?dv=win" />
OKOK

2022-07-08 03:17 UTC, zkitefly commented
与 https://github.com/LTCatt/PCL2Help/pull/210/commits/375edd25acc81de6eb83d0e95f8392d7adcce57d 的修改冲突

2022-07-14 11:10 UTC, LTCatt approved these changes

2022-07-14 11:10 UTC, merged