创建编写规范，创建Git提交帮助条目，修改一些条目
LTCatt/PCL2Help pull request #19
Opened 2021-04-10 16:04 UTC by 6get-xiaofan

2021-04-10 16:11 UTC, 6get-xiaofan commented
因为多台设备更新，导致同步出现问题，上个合并请求已关闭，但上个合并请求问题已在此请求中解决 @LTCatt

2021-04-10 16:13 UTC, 6get-xiaofan commented on 帮助/提交帮助.xaml
> -
因为提交帮助页面已相对完善，规范已单独建立条目，所以我进行了删除处理。

2021-04-13 06:27 UTC, LTCatt commented on 帮助/编写规范.xaml
> +        <local:MyCard Title="Json规范" Margin="0,0,0,15" CanSwap="True" IsSwaped="True">
不要使用嵌套 MyCard，PCL2 调用的阴影渲染无法正确处理嵌套卡片的边缘阴影。

2021-04-13 06:27 UTC, LTCatt commented on 帮助/编写规范.xaml
> +                   Text="Xaml文件 ，请在开头添加作者信息，请打开其他帮助类条目的 Xaml 查看开头的格式，具体内容规范请参阅下方 完善/修改 帮助条目 中的内容。" />
这部分没有太大必要，我们可以默认写帮助的人已经看了 json 规范的那篇帮助……可以删掉……

2021-04-13 06:27 UTC, LTCatt commented on 帮助/编写规范.xaml
> +                   Text="  · 2. 你完善/修改的内容是否不包含宣传信息？（如：包含链接到你的QQ、微信等的链接、明文出现的广告语等）" />
两个 2……

2021-04-13 06:27 UTC, LTCatt commented on 帮助/提交帮助 - Git.xaml
> +<local:MyHint Margin="0,0,0,10" Text="说明：该帮助页面已完善，请勿改动！因 Git GUI 版本不普及，将不编写进此帮助条目内，仅提供外站教程。" IsWarn="False" />
作者写在末尾。
无需标注 “该帮助页面已完善，请勿改动”。

2021-04-13 06:27 UTC, LTCatt commented on 帮助/提交帮助 - GitHub Desktop.xaml
> +                    Text="1.点击下方按钮进入 PCL 文件夹内，创建名称为：Help 的文件夹。"/>
迷之标号 1.

2021-04-13 10:56 UTC, 6get-xiaofan commented
以上问题将计划于4.16~4.17日全部解决。

2021-04-16 11:26 UTC, 6get-xiaofan commented on 帮助/自定义帮助.xaml
> +		                  EventType="打开帮助" EventData="帮助/自定义帮助 - XAML 格式.json" />
已恢复原样

2021-04-16 12:06 UTC, 6get-xiaofan commented
已解决以上问题，请求合并 @LTCatt

2021-04-16 17:38 UTC, LTCatt requested changes
此外……你的行尾啥的是不是有点问题……？为啥每个文件的 diff 都显示全文修改……
这样很难看你到底改了啥 Orz

2021-04-16 17:38 UTC, LTCatt commented on 个性化/XAML 格式.xaml
> +                   Text="下载本篇的代码" EventType="下载文件" EventData="https://6get-xiaofan.github.io/XAML-格式.xaml" ToolTip="下载本篇的代码" />
不建议使用此类域名，它在中国部分地区可能无法很好地访问 :(

2021-04-16 17:38 UTC, LTCatt commented on 帮助/提交帮助.xaml
> +		            EventType="打开帮助" EventData="帮助/编写规范.json" />
如果列了全局规范页，那就没必要在这里只列一部分了 =。=
丢个 ListItem 链接过去就行！

2021-04-17 09:32 UTC, 6get-xiaofan commented
@LTCatt 已解决问题，请求合并。
对于“为啥每个文件的差异都显示全文修改......”这点我很抱歉，可能是编辑器的原因￣▽￣，我也没有办法，我可以尝试换个编辑器

2021-04-18 06:40 UTC, merged