将图床由其它第三方图床与 jsDelivr 更换为 Backblaze B2 + Cloudflare
LTCatt/PCL2Help pull request #212
Opened 2022-07-10 12:50 UTC by z0z0r4

换掉了一些cake没换完的几个jsd图床的图
和cake商量后把它的图床也换了

手动换，可能有没换好的或者漏了的。如有404的图 请 qq: 3531890582
（不知PCL2一天有多少人访问这些图片...如果实际上线发现间接有404状况，多半是触发阈值，我即刻改配置

![image](https://user-images.githubusercontent.com/78744121/178145479-bd2afeb1-e5a0-4bf2-bf0e-70bdd0bbb6b6.png)
（看着cake的，此测速无实际意义...因为没下载图片

Example: https://cdn.img.z0z0r4.top/2022/07/10/1/explorer-saves-folder.png
![explorer-saves-folder.png](https://cdn.img.z0z0r4.top/2022/07/10/1/explorer-saves-folder.png)
~~晚点试图写个图床帮助，避免继续有人用 连接已重置 图床...~~
Co-Authored-By: Big_Cake <bigcake@cakemc.top>

2022-07-14 11:14 UTC, LTCatt reviewed
umm 考虑到被攻击的风险，我们目前不推荐使用自建图床……

2022-07-14 11:31 UTC, z0z0r4 commented
> umm 考虑到被攻击的风险，我们目前不推荐使用自建图床……

考虑到我设置了阈值，我觉得就算被攻击了，也完全可以接受
毕竟...被攻击了会自动跳到一台香港服务器，比cf的cdn快，完全无碍

考虑下合并？起码在这1T流量用完前我是不会担心攻击的 lol
（再咋说...起码也得换掉jsdelivr...

2022-07-22 07:10 UTC, Big-Cake-jpg requested changes

2022-07-22 07:33 UTC, z0z0r4 commented on Minecraft/数据包安装.xaml
> +>>>>>>> upstream/master
改了，vscode在抽风

2022-07-22 07:35 UTC, LTCatt commented
考虑到维护方便啊、安全性啊、公开程度啊之类的问题，我还是不觉得应该放在个人图床 =-=
或许可以推荐一些比较稳定的图床，然后在规范里指定使用？
@Big-Cake-jpg @z0z0r4

2022-07-23 12:01 UTC, Big-Cake-jpg commented
> 考虑到维护方便啊、安全性啊、公开程度啊之类的问题，我还是不觉得应该放在个人图床 =-=
> 
> 或许可以推荐一些比较稳定的图床，然后在规范里指定使用？
> 
> @Big-Cake-jpg @z0z0r4 

目前为止网上的很多图床服务要么稳定但速度慢，要么速度快但不久跑路。新浪图床、希沃图床等通常有防盗链限制。z0z0r4 他也说他会想办法加一个上传图片的方法。

2022-07-23 12:45 UTC, z0z0r4 commented
> 

Well, 这就到了你出场的时候了，速速找个三好图床
公开程度我没有听懂，你也许需要 https://img.z0z0r4.top。 我似乎没有设置密码
图床规范正在写，提供一个推荐图床列表
~~有生之年我也想找到个公开，高速，免费的图床。虽然有图是这么说的~~
![PI O}R9KEC_9_N5`H7I49GG](https://user-images.githubusercontent.com/78744121/180605455-12cab836-2364-4d08-ab78-db2b53520005.jpg)

2022-07-23 12:48 UTC, WTP016-CN commented
> Well, 这就到了你出场的时候了，速速找个三好图床
> 公开程度和维护方面我没有听懂，公开你也许需要 [https://img.z0z0r4.top，我似乎没有设置密码](https://img.z0z0r4.top%EF%BC%8C%E6%88%91%E4%BC%BC%E4%B9%8E%E6%B2%A1%E6%9C%89%E8%AE%BE%E7%BD%AE%E5%AF%86%E7%A0%81)
> 维护...？？？有人要帮我维护lsky吗
> 图床规范正在写，提供一个推荐图床列表
> ~~有生之年我也想找到个公开，高速，免费的图床。~~虽然有图是这么说的
> ![PI O}R9KEC_9_N5`H7I49GG](https://user-images.githubusercontent.com/78744121/180605455-12cab836-2364-4d08-ab78-db2b53520005.jpg)

可不可以给需要的帮助作者一个注册帐号的途径呢

2022-07-23 12:49 UTC, z0z0r4 commented
~~有的东西在你选择不自建而选择白嫖的时候就是明码标价的...~~

2022-07-23 12:55 UTC, z0z0r4 commented
> 



> > Well, 这就到了你出场的时候了，速速找个三好图床
> > 公开程度和维护方面我没有听懂，公开你也许需要 [https://img.z0z0r4.top，我似乎没有设置密码](https://img.z0z0r4.top%EF%BC%8C%E6%88%91%E4%BC%BC%E4%B9%8E%E6%B2%A1%E6%9C%89%E8%AE%BE%E7%BD%AE%E5%AF%86%E7%A0%81)
> > 维护...？？？有人要帮我维护lsky吗
> > 图床规范正在写，提供一个推荐图床列表
> > ~~有生之年我也想找到个公开，高速，免费的图床。~~虽然有图是这么说的
> > ![PI O}R9KEC_9_N5`H7I49GG](https://user-images.githubusercontent.com/78744121/180605455-12cab836-2364-4d08-ab78-db2b53520005.jpg)
> 
> 可不可以给需要的帮助作者一个注册帐号的途径呢

![image](https://user-images.githubusercontent.com/78744121/180605830-abaa7e61-5273-4e87-99c2-33ec9c5c38e9.png)

sorry忘了，已开启

2022-07-23 13:38 UTC, z0z0r4 commented
https://github.com/z0z0r4/PCL2Help/blob/master/%E5%B8%AE%E5%8A%A9/%E6%8F%90%E4%BA%A4%E5%B8%AE%E5%8A%A9%20-%20%E7%BC%96%E5%86%99%E8%A7%84%E8%8C%83.xaml
当前图片帮助位置
![image](https://user-images.githubusercontent.com/78744121/180607436-c5749240-4b21-4a80-aa22-0cdf4d7cf450.png)

2022-07-24 00:35 UTC, Big-Cake-jpg requested changes

2022-07-24 00:35 UTC, Big-Cake-jpg commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="  2: 添加您自己的图床则意味着已经做好防范恶意攻击的准备及承担相应的费用" />
1. 添加的图床最好是公开并符合以上要求的。若图床为私人搭建，则应该获取站长的许可。

2. 添加你自己的图床，则意味着你已经做好防范恶意攻击以及承担相应费用的准备。

2022-07-24 00:47 UTC, Big-Cake-jpg requested changes

2022-07-24 00:47 UTC, Big-Cake-jpg commented on Minecraft/数据包安装.xaml
>              <Image Margin="250,0,0,0" HorizontalAlignment="Center" Source="https://resources.cakeskin.tk/file/pcl2-image/datapack/Launch-Game.png" />
你是不是删 git 的东西的时候忘记删这些重复项目了……

2022-07-24 00:47 UTC, Big-Cake-jpg commented on Minecraft/设置分配内存大小.xaml
>          <Image HorizontalAlignment="Center" Source="https://resources.cakeskin.tk/file/pcl2-image/set-game-memory/Choose-Version.png" />
同上

2022-07-24 00:47 UTC, Big-Cake-jpg commented on Minecraft/设置分配内存大小.xaml
> +
同上

2022-07-24 00:47 UTC, Big-Cake-jpg commented on 启动器/角色皮肤导出.xaml
>  		<Image HorizontalAlignment="Center" Source="https://i.loli.net/2021/06/26/9IKCYT5HUWa43Me.png" />
同上

2022-07-25 01:19 UTC, z0z0r4 commented on Minecraft/数据包安装.xaml
>              <Image Margin="250,0,0,0" HorizontalAlignment="Center" Source="https://resources.cakeskin.tk/file/pcl2-image/datapack/Launch-Game.png" />
我可能还不太会用git吧草，多半是处理冲突的时候莫名其妙的（

2022-07-25 06:40 UTC, WTP016-CN commented
我记得我已经给这个文本做过更改了……
可以看一下 PR 吗……
https://github.com/z0z0r4/PCL2Help/pull/2

2022-07-26 14:18 UTC, z0z0r4 commented
> 我记得我已经给这个文本做过更改了…… 可以看一下 PR 吗…… [z0z0r4#2](https://github.com/z0z0r4/PCL2Help/pull/2)

我不理解为啥我 Logo 要被删掉？有什么原因吗...

2022-07-26 14:23 UTC, WTP016-CN commented
> > 我记得我已经给这个文本做过更改了…… 可以看一下 PR 吗…… [z0z0r4#2](https://github.com/z0z0r4/PCL2Help/pull/2)
> 
> 我不理解为啥我 Logo 要被删掉？有什么原因吗...

![图片](https://user-images.githubusercontent.com/66893541/181030100-c9ab3714-dabe-45f3-86d4-53a3ca635b73.png)

2022-07-27 08:39 UTC, WTP016-CN requested changes

2022-07-27 08:39 UTC, WTP016-CN commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="5. 如果有条件，请勿使用 img1 之类名称，应该使用简短明了的名称！" />
这个肯定有条件吧……
直接改成:
5. 请勿使用 img1、1等名字，请使用拼音或英文在图片名称中简要描述图片的用途。

2022-07-27 08:39 UTC, WTP016-CN commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="    ❌  img1.png" />
× img1.png
√ fabric_installer.png
√ anzhuang_fabric.png

2022-07-27 08:39 UTC, WTP016-CN commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="6. 尽量使用常见的图片格式，如 png jpg。" />
这个没有什么尽量不尽量的，如果它没看到给你用了个 heif 你也没话说，直接改成必须(
6. 使用常见的图片格式，如 png、jpg、webp 等。

2022-07-27 08:39 UTC, WTP016-CN commented on 帮助/提交帮助 - 编写规范.xaml
> +<!-- 问图片链接没地方给个注释，LTCatt 说怪话：https://a.com/1.jpg?comment=dafchsuihius 不管了 -->
???
没看懂这是啥意思

2022-07-27 08:40 UTC, WTP016-CN commented on Minecraft/数据包安装.xaml
>              <Image Margin="250,0,0,0" HorizontalAlignment="Center" Source="https://resources.cakeskin.tk/file/pcl2-image/datapack/Launch-Game.png" />
> 我可能还不太会用git吧草，多半是处理冲突的时候莫名其妙的（

用 Github Desktop (大雾

2022-08-17 09:36 UTC, LTCatt requested changes
基本上就是上面那些要求改规范的部分，弄好了就 Merge =。=

2022-08-20 09:52 UTC, z0z0r4 commented
> 基本上就是上面那些要求改规范的部分，弄好了就 Merge =。=

仍未知道你的以上指的是哪些，还有哪吗....

2022-08-20 09:56 UTC, z0z0r4 commented
tips: 图床网站部分暂时关闭，接入备案中；图片没事，照样可以下载

2022-08-20 09:57 UTC, z0z0r4 commented
tips: 图床网站部分暂时关闭，接入备案中；图片没事，照样可以下载

2022-08-20 12:01 UTC, WTP016-CN requested changes

2022-08-20 12:01 UTC, WTP016-CN commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="7. 如图片需要详细注释，可以在图片链接末尾以参数 comment=注释 为格式添加。" />
comment = 注释

2022-08-20 12:02 UTC, z0z0r4 commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="7. 如图片需要详细注释，可以在图片链接末尾以参数 comment=注释 为格式添加。" />
对于URL，不是很适合有空格吧？

2022-08-20 12:03 UTC, WTP016-CN commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="7. 如图片需要详细注释，可以在图片链接末尾以参数 comment=注释 为格式添加。" />
那就用双引号括住
“comment=注释”

2022-08-20 12:05 UTC, z0z0r4 commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="7. 如图片需要详细注释，可以在图片链接末尾以参数 comment=注释 为格式添加。" />
不理解xaml格式，""""双引号互套会不会有问题
也许我应该这样？
Text="7. 如图片需要详细注释，可以在图片链接末尾以参数 'comment=注释' 为格式添加。“

2022-08-20 12:13 UTC, z0z0r4 commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="7. 如图片需要详细注释，可以在图片链接末尾以参数 comment=注释 为格式添加。" />
修了

2022-08-20 12:13 UTC, WTP016-CN commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="7. 如图片需要详细注释，可以在图片链接末尾以参数 comment=注释 为格式添加。" />
用中文双引号就可以了

2022-08-20 12:13 UTC, z0z0r4 commented
> 基本上就是上面那些要求改规范的部分，弄好了就 Merge =。=

修了

2022-08-20 12:16 UTC, z0z0r4 commented
> 基本上就是上面那些要求改规范的部分，弄好了就 Merge =。=

修完了，不知道新版本是否已经发布能否赶上，但我肯定需要一天来观察流量...当前阈值为每天1GB
@LTCatt

2022-08-23 10:21 UTC, LTCatt requested changes
现在有合并冲突。
此外 @Big-Cake-jpg 丢出来的有的地方复读了一次的还没改。

2022-08-23 10:21 UTC, LTCatt commented on Minecraft/数据包安装.xaml
> +            <Image Margin="250,0,0,0" HorizontalAlignment="Center" Source="https://cdn.img.z0z0r4.top/2022/07/10/1/Launch-Game.png" />
这一段还在啊，你再倒腾一下啊……

2022-08-23 10:21 UTC, LTCatt commented on Minecraft/设置分配内存大小.xaml
> +        <Image HorizontalAlignment="Center" Source="https://cdn.img.z0z0r4.top/2022/07/10/1/Choose-Version.png" />
这里也是

2022-08-23 11:14 UTC, z0z0r4 commented
https://github.com/LTCatt/PCL2Help/pull/212/conflicts
这里面的是什么意思，没看懂
![image](https://user-images.githubusercontent.com/78744121/186144271-f0fb83ef-c5c8-4f7d-88f3-ffeafef9ae98.png)
看changelog没有git留下的东西啊...？

2022-08-23 11:24 UTC, z0z0r4 commented
Great, the merge conflict was resolved!

2022-08-23 11:24 UTC, z0z0r4 commented
Great, the merge conflict was resolved!
我也不知道是不是这样操作吧...寄

2022-08-23 11:27 UTC, z0z0r4 commented
草 re-request review又是什么鬼，跑了（

2022-08-25 09:34 UTC, LTCatt requested changes

2022-08-25 09:34 UTC, LTCatt commented on Minecraft/微软账号登录失败.xaml
> +
可以把你的名字加上

2022-08-25 09:34 UTC, LTCatt commented on Minecraft/微软账号登录失败.xaml
> +        <Grid>
这种地方都不需要加 Grid……这样会导致无谓的性能浪费，检查一下把所有多余的 Grid 都删掉吧……

2022-08-25 09:34 UTC, LTCatt commented on Minecraft/微软账号登录失败.xaml
> +                Text="4. 双击“Internet 协议版本 4 (TCP/IPv4)”，点击使用下面的 DNS 服务器地址，在“首选 DNS 服务器”内填写“223.5.5.5”，在“备用 DNS 服务器”内填写“223.6.6.6”，您也可选择其他国内知名 DNS 提供商提供的 DNS (如 DNSPod)。保存后按住键盘上的 Windows 键 + R 键，输入“ip
这是第 7 步吧应该……

2022-08-25 09:34 UTC, LTCatt commented on Minecraft/数据包安装.xaml
> +
迷之换行

2022-08-25 09:34 UTC, LTCatt commented on Minecraft/设置分配内存大小.xaml
> +                   Text="1. 打开您的 PCL 2 启动器，在主页点击左下方的“版本选择”按钮。" />
`PCL2` 是标准写法
不要改成 `PCL+空格+2`

2022-08-25 09:34 UTC, LTCatt commented on Minecraft/设置分配内存大小.xaml
> +                   Text="1. 打开您的 PCL 2 启动器，在主页点击上方的“设置”选单。" />
同上

2022-08-25 09:34 UTC, LTCatt commented on 帮助/提交帮助 - 编写规范.xaml
> +
迷之换行 x2……

2022-08-25 09:34 UTC, LTCatt commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="3. 在使用到 PCL2 时应使用&quot;龙猫蓝&quot;主题以确保公开版和快照版用户均可以跟随图片步骤完全准确地操作，且对应图片应随 PCL2 版本更新新版操作逻辑而随时更新。" />
3. 在添加 PCL2 截图时应使用龙猫蓝主题颜色，且不要使用自定义背景图片。

2022-08-25 09:34 UTC, LTCatt commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="  2. 如您欲将您自建的图床添加至上述列表，请您确保您有足够的资金以应对 PCL2 帮助内每日高额请求且您已做好了防范 DDoS 等恶意攻击的措施。" />
这一部分改成 XAML 注释就行，不需要直接展示在页面上

2022-08-25 09:36 UTC, z0z0r4 commented on 启动器/角色皮肤导出.xaml
> +                   Text="1. 打开您的 PCL 2 启动器，在如图所示的角色界面右键角色头像。"/>
在改了，草草草

2022-08-25 09:38 UTC, z0z0r4 commented
不懂就问，不小心点了resolve conversation，去哪里找回来

2022-08-25 09:39 UTC, z0z0r4 commented on Minecraft/微软账号登录失败.xaml
> +
> 不懂就问，不小心点了resolve conversation，去哪里找回来

找到了，邮箱，笑死

2022-08-25 09:49 UTC, z0z0r4 commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="  2. 如您欲将您自建的图床添加至上述列表，请您确保您有足够的资金以应对 PCL2 帮助内每日高额请求且您已做好了防范 DDoS 等恶意攻击的措施。" />
all over
![image](https://user-images.githubusercontent.com/78744121/186633605-a2cf087f-0bf6-4b38-9316-edb304edc1fa.png)

2022-08-25 09:51 UTC, z0z0r4 commented on 帮助/提交帮助 - 编写规范.xaml
> +                   Text="  2. 如您欲将您自建的图床添加至上述列表，请您确保您有足够的资金以应对 PCL2 帮助内每日高额请求且您已做好了防范 DDoS 等恶意攻击的措施。" />
https://github.com/LTCatt/PCL2Help/pull/212/commits/aa6b520e3995c9a6808870524a96e56e1e86a7ad

2022-08-25 13:52 UTC, LTCatt approved these changes

2022-08-25 13:52 UTC, merged

2022-08-27 12:48 UTC, z0z0r4 commented
正在进行图片压缩策略...
一个帮助页，四五张图1MB的，一眼过去加载半天
烂活啊！

2022-08-27 13:29 UTC, z0z0r4 commented
迁移完成，希望我没把图片弄丢了

2022-08-27 13:40 UTC, z0z0r4 commented
> 迁移完成，希望我没把图片弄丢了

https://github.com/LTCatt/PCL2Help/discussions/246