防止启动器被误杀
LTCatt/PCL2Help pull request #231
Opened 2022-07-20 00:42 UTC by lvjiajjjlzy

2022-07-20 12:44 UTC, WTP016-CN commented
请参考 https://github.com/LTCatt/PCL2Help/blob/master/帮助/提交帮助%20-%20编写规范.xaml
> 3、注意大小写。在中文与非中文的连接处添加一个空格（双引号除外）。使用中文标点符号（例如括号）。

2022-07-20 23:57 UTC, WTP016-CN commented on 启动器/防止误杀.xaml
> +                   Text="首先，你需要打开 gpedit.msc 这个程序，你可以按 下win+r 来启动这个程序，也可以在下面启动。" />
使用规范术语: Windows 键+ R 键

2022-07-20 23:58 UTC, WTP016-CN commented on 启动器/防止误杀.xaml
> +        <local:MyButton Margin="0,8,0,8" Width="200" Height="35"
这个按钮应当放在上方打开 gpedit.msc 下方
Windows 10 家庭版无组策略管理器，应当增加其他方法

2022-07-20 23:59 UTC, WTP016-CN commented on 启动器/防止误杀.json
> +    "Description": "帮助你解决启动器总被Windows安全中心误杀的烦恼",
请手动点击已解决

2022-07-20 23:59 UTC, WTP016-CN commented
部分过时 request changes 请作者手动点击解决

2022-07-21 00:03 UTC, WTP016-CN commented on 启动器/防止误杀.xaml
> +                   Text="首先，你需要打开 gpedit.msc 这个程序，你可以按 下win+r 来启动这个程序，也可以在下面启动。" />
下字前面的空格删掉

2022-07-21 00:12 UTC, Big-Cake-jpg commented
不需要用组策略吧……而且家庭版 Windows 没有组策略。
Microsoft Defender 应用内已经有了更加方便的排除项设置了。位于`病毒与威胁防护->排除项`内。

2022-07-21 00:14 UTC, WTP016-CN commented
且大部分国内用户不使用 Microsoft Defender
建议加上其他杀毒软件增加白名单方法
个人觉得这个教程发在这也没什么人都会看
毕竟都误杀了还怎么打开这个教程呢（（

2022-07-21 01:40 UTC, Big-Cake-jpg commented
> 且大部分国内用户不使用 Microsoft Defender
> 
> 建议加上其他杀毒软件增加白名单方法
> 
> 个人觉得这个教程发在这也没什么人都会看
> 
> 毕竟都误杀了还怎么打开这个教程呢（（

但是我用 Defender（

2022-07-21 02:27 UTC, lvjiajjjlzy commented
> 且大部分国内用户不使用 Microsoft Defender 建议加上其他杀毒软件增加白名单方法 个人觉得这个教程发在这也没什么人都会看 毕竟都误杀了还怎么打开这个教程呢（（

对此只能说，想要系统纯净一点的，都不会去用其他杀毒软件，火绒除外，而且其他杀毒软件白名单很容易添加吧，Windows的藏得有点深

2022-07-21 02:30 UTC, WTP016-CN requested changes

2022-07-21 02:30 UTC, WTP016-CN commented on 启动器/防止误杀.xaml
> +<local:MyCard Title="防止Windows 安全中心误报">
加空格

2022-07-21 02:30 UTC, WTP016-CN commented on 启动器/防止误杀.xaml
> +                   Text="然后点击”’病毒和威胁防护‘设置 “下的“管理设置”。" />
然后点击“病毒和威胁防护设置”下的“管理设置”。

2022-07-21 02:30 UTC, WTP016-CN commented on 启动器/防止误杀.xaml
> +                   Text="找到并点击“添加或删除排除项”，并添加排除项。分别在“文件”和“进程”中添加启动器路径。如图所示" />
删掉如图所示

2022-07-22 07:38 UTC, LTCatt requested changes
首先吧，如果启动器被误杀了，他们根本不可能看到这个帮助………………
所以唯一能有用的情况就是升级失败。
或许应该把整体描述改为如果启动器因为 Windows 防火墙导致升级失败应该怎么办。
启动器对这种情况现在有针对性检查，会提示“由于 Windows 防火墙拦截了更新操作，PCL2 无法完成更新，请在将 PCL2 添加入白名单或关闭防火墙后再试！”

2022-08-12 06:37 UTC, JimmyzZZ-CN commented
从安全软件的角度分析一下吧。
首先，我不得不说的是，国内大部分人要么火绒要么360，还有一些金山毒霸、腾讯。考虑到PCL2主要面对国内用户，首先向这几家提交白名单是很重要的。
其次，一些对安全较有研究的人会选择卡巴斯基、Norton、BitDefender、智量等等等。卡巴斯基我遇到过一次云机器学习（VHO）杀PCL2的联机文件，我尝试提交False Positive但是卡巴斯基拒绝加白。
怎么说呢，其实如果混淆过的.NET文件还是很容易造成FP的。尤其是安全软件的机器学习，这是一个黑盒，不好处理。

关于误报这方面首先可以在下载的时候进行一定提示，让用户选择是否信任。其次可以向各大安全软件厂商申请加白，但是.NET文件如果没有混淆的话，应该会进行一定人工分析，强混淆的话我不确定是否会加白。毕竟雷鸟下载的强混淆让智量的工程师分析不出来，最后也没能加白。

2022-08-12 08:02 UTC, closed without merging