搬迁图片、更新图片至 PCL2 最新版本并重写文本
LTCatt/PCL2Help pull request #235
Opened 2022-07-25 07:22 UTC by WTP016-CN

2022-08-17 09:40 UTC, LTCatt requested changes
等 #212 倒腾完了一起合并吧

2022-08-17 09:40 UTC, LTCatt commented on Minecraft/微软账号登录失败.xaml
> +                Text="3. 右键点击您目前正在连接的网络(一般为&quot;以太网&quot;或&quot;WLAN&quot;)，点击属性。" />
不要使用英文括号……

2022-08-17 09:40 UTC, LTCatt commented on Minecraft/整合包安装.xaml
> +                   Text="整合包(Modpack)是包含已经配置好的、可能包含剧情的、包含 Mod 的 Minecraft 游戏整合文件。" />
英文括号

2022-08-23 10:18 UTC, LTCatt approved these changes

2022-08-23 10:18 UTC, merged

2022-08-27 02:11 UTC, z0z0r4 commented
水印，草