搬运PCL2 常见问题 兼 脑溢血急救中心
LTCatt/PCL2Help pull request #247
Opened 2022-08-30 04:20 UTC by GBC034

太肝了=。=

2022-08-30 04:24 UTC, GBC034 commented
请了一个朋友一起做的（https://github.com/Fiorest009）

2022-08-30 04:29 UTC, Big-Cake-jpg requested changes
我认为需要改的就这些，剩下的地方得看龙猫的意见了

2022-08-30 04:29 UTC, Big-Cake-jpg commented on 启动器/HelpDoc/Minecraft.json
> +    "Description":"让你的Minecraft游戏更加方便且精彩",
Minecraft 与其他文字之间需要空格隔开

2022-08-30 04:29 UTC, Big-Cake-jpg commented on 启动器/HelpDoc/PCL2 常见问题 兼 脑溢血急救中心.json
> +    "Types": ["PCL2常见问题 兼 脑溢血急救中心"]
删去脑溢血急救中心相关字样

2022-08-30 04:29 UTC, Big-Cake-jpg commented on 启动器/HelpDoc/PCL2 常见问题 兼 脑溢血急救中心.xaml
> +<local:MyCard Title="PCL2 常见问题 兼 脑溢血急救中心" CanSwap="False">
同上

2022-08-30 04:40 UTC, GBC034 commented
OK

2022-08-30 04:41 UTC, GBC034 commented
@LTCatt @Fiorest009

2022-08-30 04:42 UTC, Fiorest009 commented
What
- 愿星光照亮你的前程 -

May it be an evening star shines down upon you

________________________________
发件人: GBC034 ***@***.***>
发送时间: Tuesday, August 30, 2022 12:41:47 PM
收件人: LTCatt/PCL2Help ***@***.***>
抄送: Fiorest ***@***.***>; Mention ***@***.***>
主题: Re: [LTCatt/PCL2Help] 搬运PCL2 常见问题 兼 脑溢血急救中心 (PR #247)


@LTCatt<https://github.com/LTCatt> @Fiorest009<https://github.com/Fiorest009>

―
Reply to this email directly, view it on GitHub<https://github.com/LTCatt/PCL2Help/pull/247#issuecomment-1231132936>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXMXVQ4OJRVGLEX65H5VT43V3WGIXANCNFSM6AAAAAAQAALZS4>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-08-30 04:43 UTC, Fiorest009 commented
OK，下午来改一下

2022-08-30 04:44 UTC, GBC034 commented
> OK，下午来改一下

改完了。。。

2022-08-30 04:46 UTC, GBC034 commented
因为龙猫日更文档，所以有些地方还没来得及改=。=（tired

2022-08-30 04:48 UTC, Fiorest009 commented
还有些地方没做完，我下午再补全一下，龙猫昨天更新的文档后面还没完善

2022-08-30 04:49 UTC, Fiorest009 commented
但是主题和赞助的更改我已经弄完了

2022-08-30 05:14 UTC, GBC034 commented
还想请问有没有大佬知道怎么判断public和snapshot，现在制作整合包指南默认链接的是public版本

2022-08-30 10:53 UTC, LTCatt requested changes
我先大概说一下……
- 不要用乱码文件名。
- 很多和赞助相关的不要放进帮助库，例如 `如何加入群 小游戏/生存 服务器？` 以及 `在找管理的时候要注意什么？` 等。帮助库是主要面向 **未赞助的** 用户的……
- 很多和已有帮助重叠的部分也不要放进来，例如 `如何安装资源包、材质包、地图、Mod、光影、整合包……` 等。
- 删除一些明显不会起到帮助效果的东西，例如 `PCL2 打不开怎么办？`……还有 `PCL2 安装整合包或 Forge 失败，报错中包含“文件 MD5 应为 XXXXXX”怎么办？`：这个问题只会在老版本 PCL2 中出现，所以如果用户看得到这条帮助，那么肯定没有这个问题……
- 不要在一个文件里放多个帮助条目，建议一个问题做一个文件。现在这样大家在搜索自己的问题的时候很难直观找到对应项目。
- 不要使用 StackPanel 混搭文本与超链接，这种混搭形式不兼容自动换行，在文本超出一行时会出现严重的显示问题。需要加超链接的时候，请直接使用纯文本的 Text，然后在下方再单独放一个打开链接的按钮（或者视情况直接删除链接）。


总的来说，帮助库是面向未赞助者的，只应该收录脑溢血文档里的 **一小部分** 对大家都有用的内容，例如 `PCL2 的 Mod 下载中找不到某个 Mod 怎么办？`。换而言之，脑溢血文档里的绝大部分内容都不适合放进帮助库。
关于这种一两句话就能解释的问题，直接使用点击后弹窗的帮助条目（例如现在的 `解锁隐藏主题`），每个问题单独开一个 json 文件就行。

还是辛苦各位了 Orz

2022-08-30 10:53 UTC, LTCatt commented on 启动器/HelpDoc/SepPage/0hDr.json
> +}
不要使用乱码文件名。

2022-08-30 10:59 UTC, Fiorest009 commented on 启动器/HelpDoc/SepPage/0hDr.json
> +}
OK，收到收到

2022-08-31 11:16 UTC, GBC034 commented on 启动器/HelpDoc/SepPage/0hDr.json
> +}
解决了一部分
剩下还在处理

2022-08-31 12:20 UTC, GBC034 commented on 启动器/HelpDoc/SepPage/0hDr.json
> +}
> 我先大概说一下……
> 
> * 不要用乱码文件名。
> * 很多和赞助相关的不要放进帮助库，例如 `如何加入群 小游戏/生存 服务器？` 以及 `在找管理的时候要注意什么？` 等。帮助库是主要面向 **未赞助的** 用户的……
> * 很多和已有帮助重叠的部分也不要放进来，例如 `如何安装资源包、材质包、地图、Mod、光影、整合包……` 等。
> * 删除一些明显不会起到帮助效果的东西，例如 `PCL2 打不开怎么办？`……还有 `PCL2 安装整合包或 Forge 失败，报错中包含“文件 MD5 应为 XXXXXX”怎么办？`：这个问题只会在老版本 PCL2 中出现，所以如果用户看得到这条帮助，那么肯定没有这个问题……
> * 不要在一个文件里放多个帮助条目，建议一个问题做一个文件。现在这样大家在搜索自己的问题的时候很难直观找到对应项目。
> * 不要使用 StackPanel 混搭文本与超链接，这种混搭形式不兼容自动换行，在文本超出一行时会出现严重的显示问题。需要加超链接的时候，请直接使用纯文本的 Text，然后在下方再单独放一个打开链接的按钮（或者视情况直接删除链接）。
> 
> 总的来说，帮助库是面向未赞助者的，只应该收录脑溢血文档里的 **一小部分** 对大家都有用的内容，例如 `PCL2 的 Mod 下载中找不到某个 Mod 怎么办？`。换而言之，脑溢血文档里的绝大部分内容都不适合放进帮助库。 关于这种一两句话就能解释的问题，直接使用点击后弹窗的帮助条目（例如现在的 `解锁隐藏主题`），每个问题单独开一个 json 文件就行。
> 
> 还是辛苦各位了 Orz

我打算在赞助后的用户（快照版）显示，而正式版不显示（"ShowInPublic":false）
然后其他的每个问题单独做一个xaml和json
乱码的文件名正在改，当时为了跟网页文档定位页面系统匹配（https://shimo.im/docs/qKPttVvXKqPD8YDC#anchor-XXXX）所以文件名就为anchor-后面的四个字母，改了也无妨
其他的待定

2022-08-31 13:19 UTC, GBC034 commented
有些地方可能要调用PCL2内部的文件，例如`反馈`，`更新`等，请龙猫给一下内部链接，谢谢
顺便说个事，因为有些xaml不在帮助主页上显示，所以没有填types，只能用{path}来定位该json，不知道PCL2更新后内部会不会报错（我记得Help文件夹是Resources下的一个zip

2022-08-31 13:29 UTC, GBC034 commented
@Fiorest009 Merge后一定通知你

2022-09-03 09:07 UTC, WTP016-CN commented
周末了，我帮忙改一下，发个 PR……

2022-09-03 09:08 UTC, WTP016-CN commented
在 启动器/HelpDoc/版本与更新 文件夹内大部分东西都无需使用单独的帮助文档，使用 EventData 为弹出窗口的 json 文档就可以了……

2022-09-03 09:09 UTC, WTP016-CN commented
许多内容原帮助库就有，无需重复造轮子，例如 启动器/HelpDoc/登录

2022-09-03 09:12 UTC, WTP016-CN commented
有了 TextWrapping 属性的 TextBlock 无需手动将文本分段

2022-09-03 09:25 UTC, WTP016-CN commented
> 有些地方可能要调用PCL2内部的文件，例如`反馈`，`更新`等，请龙猫给一下内部链接，谢谢 顺便说个事，因为有些xaml不在帮助主页上显示，所以没有填types，只能用{path}来定位该json，不知道PCL2更新后内部会不会报错（我记得Help文件夹是Resources下的一个zip

无需使用{path} 直接输入此文件在 Github 项目内的绝对位置即可

2022-09-03 09:26 UTC, WTP016-CN commented
> public

在 json 文件中输入 "ShowInPublic" 和 "ShowInSnapshot"
一般来说只使用"ShowInPublic"即可满足大部分的需求

2022-09-03 09:40 UTC, WTP016-CN commented
交 PR 之前请检查是否可用
我随便翻翻就翻出了一堆由于{path}调用方式导致无法使用的错误……

2022-09-03 09:58 UTC, GBC034 commented
> > 有些地方可能要调用PCL2内部的文件，例如`反馈`，`更新`等，请龙猫给一下内部链接，谢谢 顺便说个事，因为有些xaml不在帮助主页上显示，所以没有填types，只能用{path}来定位该json，不知道PCL2更新后内部会不会报错（我记得Help文件夹是Resources下的一个zip
> 
> 无需使用{path} 直接输入此文件在 Github 项目内的绝对位置即可

尝试过，但是要报错

2022-09-05 00:23 UTC, GBC034 commented
finish :D

2022-09-05 00:35 UTC, Fiorest009 commented
finish :D

2022-09-06 02:27 UTC, GBC034 commented
......(phew

2022-09-07 06:44 UTC, LTCatt requested changes
求求你们仔细看看页面格式要求，别自己搞花样了，真的谢谢……

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/SepPage/更新 PCL2.xaml
> +<local:MyCard Title="正式版" Margin="0,0,0,15">
就，感觉你们没懂我的意思……这种一两句话就能解决的直接用一个弹窗来处理，不要单独开 xaml 页面

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/SepPage/更新 PCL2.json
> +    "Title": "有关更新 PCL2 的说明",
这种不适用于帮助库的标题，“获取 PCL2 更新” 比 “XXX 的说明” 就要好很多

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/SepPage/网络环境问题的解答.xaml
> +            <TextBlock Text="国外" Margin="0,15,0,0" Background="{DynamicResource ColorBrush5}" />
没必要这样处理加粗，不加粗就行了……

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/SepPage/网络环境问题的解答.xaml
> +            <TextBlock Text="国外" Margin="0,15,0,0" Background="{DynamicResource ColorBrush5}" />
……你要留着也行（叹气

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/PCL2 帮助文档.json
> +}
我们已经有了一条 “赞助与内测指南”，完全重复了……
在加之前能不能看看有没有重……

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.json
> +    "Logo": "pack://application:,,,/images/Blocks/GrassPath.png",
GrassPath 图标是用于弹窗类型的，有独立页面应该用 Grass

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.json
> +    "ShowInSnapshot": false
这是在干啥？都不显示？

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.json
> +    "Types" : ["PCL2 常见问题"],
大哥，帮助库里面的都是常见问题，这个分类有啥意义么

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.json
> +	"Title": "QQ 群",
Title 单独写个 “QQ 群”，而不加详细描述，根本没有任何意义……

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.json
> +	"Title": "QQ 群",
你就算是改成 “QQ 群相关问题” 都比只在标题写个 “QQ 群” 好得多……

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.json
> +    "Keywords":"QQ群内测群",
我前面说了，这种 **只和赞助者有关** 的内容不要放进帮助库，帮助库的内容需要对 **非赞助者** 也有作用，所以脑溢血文档里 **绝大多数** 的东西都不要搬进来！

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.xaml
> +           <!--投稿回声洞 -->            <TextBlock TextWrapping="Wrap" LineHeight="17" Margin="0,0,0,0"
这个注释是在干啥？

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.xaml
> +                        <TextBlock TextWrapping="Wrap" LineHeight="17" Margin="0,0,0,0"
不要使用 FontWeight="SemiBold" 这种参数，FontWeight 的呈现效果根据系统和字体是不确定的，在适当的时候直接放弃加粗就行，不用特别在意加粗

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.xaml
> +                <StackPanel Orientation="Horizontal">
之前说过了，不要在文本部分用横向的 StackPanel，这在你的内容超过一行字的时候会出现显示问题，考虑到统一性，就算内容不到一行也不要这样做。
出现的超链接可以用按钮（MyButton）单独附加在下面。

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.xaml
> +                <TextBlock TextWrapping="Wrap" LineHeight="17" Margin="0,0,0,0"
Margin="0,0,0,0" 是无意义的。

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/QQ 群.xaml
> +
顺带一提，所有有关 QQ 群的内容都是 **只和赞助者有关** ，都不满足收入帮助库的标准，这些部分都应该删掉。

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/下载/Para1.xaml
> +        <local:MyListItem Margin="15,0,0,15" Type="Clickable" EventType="打开帮助" EventData="{path}/PCL/Help/PCL2Help/启动器/HelpDoc/SepPage/更新 PCL2.json" />
这个 EventData 是错的，这是在搞啥……你看看其他帮助文档是咋弄的……

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/下载/Para1.json
> +{
即使是内链，也不要使用 “Para1” 这种无意义的文件名！

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/主题.xaml
> +<local:MyCard Title="下载" Margin="0,0,0,15">
下载？

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/赞助/Para3.json
> +    "Title": "在赞助 54.32 档位后，要如何分享 23.33 档位给他人？",
借鉴现有页面标题的格式，标题应该改为陈述句。
此外这种只和赞助者有关的内容也应该删掉（

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/识别码与解锁码/Para1.json
> +    "keywords":"识别码与解锁码"
已经出现在 Title 的内容不要放进 Keywords，详见 json 格式的说明，这是用来 **补充** 可能被用于搜索，但是没在 title 和 desc 里出现的字的。

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/识别码与解锁码.json
> +    "Ketwords":"解锁码和识别码",
Ketwords？

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/识别码与解锁码.json
> +	"Title": "识别码与解锁码",
缩进错了

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/杂项/Para3.json
> +    "Logo": "pack://application:,,,/images/Blocks/Fabric.png",
这个 Logo 是什么鬼？json 格式指引的哪个地方允许帮助库用这些 Logo 了？

2022-09-07 06:44 UTC, LTCatt commented on 启动器/HelpDoc/杂项/Para1.xaml
> +        <local:MyButton Width="200" Height="35" HorizontalAlignment="Left" Padding="13,0,13,0"
这种都关了的明显没必要的就别放进帮助库了啊……
自己取舍一下嘛 =。=

2022-09-07 08:11 UTC, GBC034 commented on 启动器/HelpDoc/下载/Para1.json
> +{
Paragraph1,实在想不出来了

2022-09-07 08:12 UTC, closed without merging