添加：双方能否使用用同一个凭证？
LTCatt/PCL2Help pull request #253
Opened 2022-10-22 17:17 UTC by zkitefly

2022-10-22 23:50 UTC, Big-Cake-jpg commented
帮助库的更改请前往 LTCatt/PCL2Help 仓库提交 Pull Request。

2022-10-23 10:27 UTC, LTCatt requested changes
可以参考 https://shimo.im/docs/KrkEVXz1K0frowAJ#anchor-9F26 这几段再详细改改 =。=

2022-10-29 04:34 UTC, zkitefly commented
zkitefly requested review from @LTCatt 12 hours ago

2022-11-01 15:26 UTC, LTCatt approved these changes

2022-11-01 15:26 UTC, merged