修改LS相关帮助
LTCatt/PCL2Help pull request #262
Opened 2022-12-23 01:38 UTC by Wishing-Qi

2022-12-23 03:33 UTC, Big-Cake-jpg requested changes

2022-12-23 03:33 UTC, Big-Cake-jpg commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="如果您想在多人游戏中展示您的皮肤，请保证所有参与联机的成员均使用 LittleSkin 外置登录，或搭配Custom Skin Loader模组并添加ExtraList文件（仅当皮肤显示不正常时）以达到相同的效果" IsWarn="True" />
CustomSkinLoader 与其他内容间需用空格隔开，且 Custom、Skin、Loader 之间不需要用空格

2022-12-23 03:33 UTC, Big-Cake-jpg commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyButton Margin="0,10,0,0" MinWidth="280" Padding="13,0" HorizontalAlignment="Left" Height="35" Text="获取配置文件（须登录Littleskin）" EventType="打开网页" EventData="https://littleskin.cn/user/conf
删除括号内内容可能更好点？

S 大写，英文与中文之间用空格隔开

2022-12-23 03:33 UTC, Big-Cake-jpg commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="请在注册 Littleskin 账号时不要使用第三方登录，这可能会导致您的账号无法设置密码从而无法继续操作" IsWarn="False" />
S 大写

2022-12-23 03:33 UTC, Big-Cake-jpg commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,20,0,0" Text="另请注意：LittleSkin 外置登录本质上仍然是离线登录，不能用于进入正版服务器，也请不要以“我使用来自 LittleSkin 的外置登录之后无法进入Hypixel之类的正版服务器“一类的问题向LittleSkin进行反馈" IsWarn="True" />
补空格

2022-12-23 05:23 UTC, LTCatt requested changes

2022-12-23 05:23 UTC, LTCatt commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,20,0,0" Text="另请注意：LittleSkin 外置登录本质上仍然是离线登录，不能用于进入正版服务器，也请不要以“我使用来自 LittleSkin 的外置登录之后无法进入Hypixel之类的正版服务器“一类的问题向LittleSkin进行反馈" IsWarn="True" />
“不要以“我使用来自 LittleSkin 的外置登录之后无法进入Hypixel之类的正版服务器“一类的问题向LittleSkin进行反馈” 这段可以删掉，这是帮助文档……

2022-12-23 05:23 UTC, LTCatt commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <TextBlock Margin="0,50,0,0" Text="3. 在弹出的窗口内输入角色名(这将会成为联机时的ID,也即游戏中的用户名)，填写完成后点击“确定”" />
改为中文标点

2022-12-23 09:22 UTC, LTCatt requested changes

2022-12-23 09:22 UTC, LTCatt commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="如果您想在多人游戏中展示您的皮肤，请保证所有参与联机的成员均使用 LittleSkin 外置登录，或搭配 CustomSkinLoader 模组并添加 ExtraList 文件（仅当皮肤显示不正常时）以达到相同的效果" IsWarn="True" />
在卡片直接写这些内容，连着放三条 Warn Hint 是什么鬼……

2022-12-23 09:22 UTC, LTCatt commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <TextBlock Margin="0,50,0,0" Text="3. 在弹出的窗口内输入角色名（这将会成为联机时的ID,也即游戏中的用户名），填写完成后点击“确定”" />
英文逗号……

2022-12-23 11:41 UTC, Wishing-Qi commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="如果您想在多人游戏中展示您的皮肤，请保证所有参与联机的成员均使用 LittleSkin 外置登录，或搭配 CustomSkinLoader 模组并添加 ExtraList 文件（仅当皮肤显示不正常时）以达到相同的效果" IsWarn="True" />
虽然但是，最近用ls进正版服的人未免有点多，ls离线登录那条我认为需要保留

2022-12-23 12:29 UTC, ComputerCPT commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="如果您想在多人游戏中展示您的皮肤，请保证所有参与联机的成员均使用 LittleSkin 外置登录，或搭配 CustomSkinLoader 模组并添加 ExtraList 文件（仅当皮肤显示不正常时）以达到相同的效果" IsWarn="True" />
为什么要展示皮肤得保证**所有人**都是用LittleSkin外置登录的？

2022-12-23 14:27 UTC, Wishing-Qi commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="如果您想在多人游戏中展示您的皮肤，请保证所有参与联机的成员均使用 LittleSkin 外置登录，或搭配 CustomSkinLoader 模组并添加 ExtraList 文件（仅当皮肤显示不正常时）以达到相同的效果" IsWarn="True" />
这是littleskin的配置教程欸，别人不用当然看不到了

2022-12-24 00:52 UTC, ComputerCPT commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="如果您想在多人游戏中展示您的皮肤，请保证所有参与联机的成员均使用 LittleSkin 外置登录，或搭配 CustomSkinLoader 模组并添加 ExtraList 文件（仅当皮肤显示不正常时）以达到相同的效果" IsWarn="True" />
> 这是littleskin外置登录配置教程，别人不用当然看不到了

还是觉得有点怪，难道一定要**所有人**，而不是只有**想看到你皮肤的人**用LittleSkin外置登录才能看到皮肤吗

2022-12-24 03:41 UTC, Wishing-Qi commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="如果您想在多人游戏中展示您的皮肤，请保证所有参与联机的成员均使用 LittleSkin 外置登录，或搭配 CustomSkinLoader 模组并添加 ExtraList 文件（仅当皮肤显示不正常时）以达到相同的效果" IsWarn="True" />
> > 这是littleskin外置登录配置教程，别人不用当然看不到了
> 
> 还是觉得有点怪，难道一定要**所有人**，而不是只有**想看到你皮肤的人**用LittleSkin外置登录才能看到皮肤吗

这里不考虑服务器相关情况，服务器如果启用了外置登录（除个别混合登录服），那一定是所有人都使用了来自同一个皮肤站的外置登录，个别好友联机的话，一般你也会想要他们看到你的皮肤；其次，我个人感觉**想看到你皮肤的成员均使用 LittleSkin 外置登录**比**所有参与联机的成员**读起来更怪，我暂时找不到合适的替换词句

2022-12-25 06:11 UTC, Big-Cake-jpg approved these changes
我的行为仅供参考，以龙猫的回复为准。

2022-12-25 19:19 UTC, LTCatt approved these changes

2022-12-25 19:19 UTC, merged

2022-12-28 00:31 UTC, ComputerCPT commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="如果您想在多人游戏中展示您的皮肤，请保证所有参与联机的成员均使用 LittleSkin 外置登录，或搭配 CustomSkinLoader 模组并添加 ExtraList 文件（仅当皮肤显示不正常时）以达到相同的效果" IsWarn="True" />
> > > 这是littleskin外置登录配置教程，别人不用当然看不到了
> > 
> > 
> > 还是觉得有点怪，难道一定要**所有人**，而不是只有**想看到你皮肤的人**用LittleSkin外置登录才能看到皮肤吗
> 
> 这里不考虑服务器相关情况，服务器如果启用了外置登录（除个别混合登录服），那一定是所有人都使用了来自同一个皮肤站的外置登录，个别好友联机的话，一般你也会想要他们看到你的皮肤；其次，我个人感觉**想看到你皮肤的成员均使用 LittleSkin 外置登录**比**所有参与联机的成员**读起来更怪，我暂时找不到合适的替换词句

虽然这个Pull requests close了，但还是想说一下替换词句或许可以改主语，把他人当做主语，也许可以……：如果您想在多人游戏中展示您的皮肤，请记住只有与您同样使用LS外置登录的玩家才能看到你的LS皮肤，或在……（我不知道这是客户端还是服务端）端中……（加上后面的内容）

> > > 这是littleskin外置登录配置教程，别人不用当然看不到了
> > 
> > 
> > 还是觉得有点怪，难道一定要**所有人**，而不是只有**想看到你皮肤的人**用LittleSkin外置登录才能看到皮肤吗
> 
> 这里不考虑服务器相关情况，服务器如果启用了外置登录（除个别混合登录服），那一定是所有人都使用了来自同一个皮肤站的外置登录，个别好友联机的话，一般你也会想要他们看到你的皮肤；其次，我个人感觉**想看到你皮肤的成员均使用 LittleSkin 外置登录**比**所有参与联机的成员**读起来更怪，我暂时找不到合适的替换词句

虽然这个Pull requests close了，但还是想说一下替换词句或许可以改主语，把他人当做主语，也许可以……：如果您想在多人游戏中展示您的皮肤，请记住只有与您同样使用LS外置登录的玩家才能看到你的LS皮肤，或在……（我不知道这是客户端还是服务端）端中……（加上后面的内容）

2022-12-28 00:32 UTC, ComputerCPT commented on 启动器/LittleSkin 外置登录使用教程.xaml
> +        <local:MyHint Margin="0,10,0,0" Text="如果您想在多人游戏中展示您的皮肤，请保证所有参与联机的成员均使用 LittleSkin 外置登录，或搭配 CustomSkinLoader 模组并添加 ExtraList 文件（仅当皮肤显示不正常时）以达到相同的效果" IsWarn="True" />
> > > 这是littleskin外置登录配置教程，别人不用当然看不到了
> > 
> > 
> > 还是觉得有点怪，难道一定要**所有人**，而不是只有**想看到你皮肤的人**用LittleSkin外置登录才能看到皮肤吗
> 
> 这里不考虑服务器相关情况，服务器如果启用了外置登录（除个别混合登录服），那一定是所有人都使用了来自同一个皮肤站的外置登录，个别好友联机的话，一般你也会想要他们看到你的皮肤；其次，我个人感觉**想看到你皮肤的成员均使用 LittleSkin 外置登录**比**所有参与联机的成员**读起来更怪，我暂时找不到合适的替换词句

虽然这个Pull requests close了，但还是想说一下替换词句或许可以改主语，把他人当做主语，也许可以……：如果您想在多人游戏中展示您的皮肤，请记住只有与您同样使用LS外置登录的玩家才能看到你的LS皮肤，或在……（我不知道这是客户端还是服务端）端中……（加上后面的内容）