更新了 VSCode 获取帮助库 的教程
LTCatt/PCL2Help pull request #272
Opened 2023-02-01 09:17 UTC by huangminzhe

补充了 VSCode 获取帮助库 的教程

2023-02-01 12:56 UTC, LTCatt requested changes

2023-02-01 12:56 UTC, LTCatt commented on Minecraft/新手教程.json
> +	"EventData": "https://minecraft.fandom.com/zh/wiki/%E6%95%99%E7%A8%8B"
请保留 B 站 wiki 不作更改。
Fandom Wiki 在国内可能无法访问，对于新手的教程还是能确保访问更重要。

2023-02-01 12:56 UTC, LTCatt commented on 百科/Minecraft Wiki.json
> +	"EventData": "https://minecraft.fandom.com/zh/wiki/Minecraft_Wiki"
请保留 B 站 wiki 不作更改。
Fandom Wiki 在国内可能无法访问，对于新手的教程还是能确保访问更重要。

2023-02-01 13:16 UTC, WTP016-CN requested changes
建议更改部分措辞。

2023-02-01 13:16 UTC, WTP016-CN commented on Minecraft/新手教程.json
> +    "__Author__": "XiaoFans、龙腾猫跃、huangminzhe",
请在更改为 Bilibili Wiki 后删除此作者标记。

2023-02-01 13:16 UTC, WTP016-CN commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="4. 复制你 Fork 的仓库地址，粘贴到指令输入框回车执行 Clone 操作复制仓库。"/>
请更改措辞并补充完整如何获取 Fork 仓库地址。
打开 Github Fork 仓库，点击右上角 Code 后复制仓库的 Git 链接，在 VSCode 主界面按下 F1（对于部分笔记本应按 Fn + F1）打开指令输入框，输入“Git Clone”并回车。

2023-02-01 13:16 UTC, WTP016-CN commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="4. 复制你 Fork 的仓库地址，粘贴到指令输入框回车执行 Clone 操作复制仓库。"/>
粘贴 Fork 仓库的 Git 链接后至指令输入框后按下回车键执行 Clone 操作克隆 Fork 仓库至本地。

2023-02-01 13:52 UTC, huangminzhe commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="4. 复制你 Fork 的仓库地址，粘贴到指令输入框回车执行 Clone 操作复制仓库。"/>
修改完了![9U @0VCB~C3ZNU9TXB7P}OS](https://user-images.githubusercontent.com/107444508/216061694-b08616c3-b2f3-4a1f-adf2-a68a65e124be.png)

2023-02-02 06:47 UTC, LTCatt approved these changes

2023-02-02 06:47 UTC, merged