更改MC百科名称；更新git版本；扔到美化网站上
LTCatt/PCL2Help pull request #274
Opened 2023-02-17 13:59 UTC by RawDiamondMC

2023-02-17 16:59 UTC, LTCatt requested changes

2023-02-17 16:59 UTC, LTCatt commented on 百科/MCMOD.json
> +	"Title": "MC百科",
加个空格：MC(空格)百科

2023-02-17 16:59 UTC, LTCatt commented on 帮助/提交帮助 - Git.json
> +	"__Author__": "XiaoFans、龙腾猫跃、林小槐、WTP016、RawDiamondMC",
少量修改不要把自己加进 Author 里

2023-02-18 06:52 UTC, RawDiamondMC commented
已更改

2023-02-18 11:36 UTC, merged