更新登录方面的帮助文档
LTCatt/PCL2Help pull request #276
Opened 2023-02-20 13:36 UTC by youzi-2333

~~又是被 Git 折磨的一天~~ 改的东西有点多，下面大致说一下……

以下行号均为修改后的行号。
- 启动器/指定登录方式.xaml
  - 行 1：更新“还需要进一步完善”的提示为标准格式；
  - 行 15-25：更新了图片，主要为了迎合 帮助库编写规范——图片规范 第 3 条，使用龙猫蓝主题颜色，且不使用背景图片；并且截图更新为最新版本的 PCL2 正式版；
  - 行 29：改了一下标题，如果觉得原来那个比较好的话也可以改回去……
- 启动器/LittleSkin 外置登录使用教程.xaml
  - 行 6-9：改掉了一些 `MyHint`；
  - 行 34-50：更新了图片，主要为了迎合 帮助库编写规范——图片规范 第 3 条，使用龙猫蓝主题颜色，且不使用背景图片；并且截图更新为最新版本的 PCL2 正式版；统一了 PCL2 的窗口大小、背景图片等。

如果觉得有些修改没必要的话可以改回去.jpg

2023-02-20 20:07 UTC, LTCatt requested changes

2023-02-20 20:07 UTC, LTCatt commented on 启动器/指定登录方式.xaml
>  <!-- 需要根据规范重新整理格式、标点、空格等。部分语句不太通顺，需要再改改。 -->
可以删了 √

2023-02-20 20:07 UTC, LTCatt commented on 启动器/指定登录方式.xaml
>  </local:MyCard>
没有必要添加简介，点进这个页面的用户已经知道了

2023-02-20 20:07 UTC, LTCatt commented on 启动器/LittleSkin 外置登录使用教程.xaml
>          <local:MyButton Margin="0,10,0,0" MinWidth="140" Padding="13,0" HorizontalAlignment="Left" Height="35" Text="打开网页版教程" EventType="打开网页" EventData="https://note.youdao.com/s/fHxFNnq" />
@bling-yshs 看一看对着改改？
其实我感觉没有必要这样，额外开一个网页也蛮复杂的……其实也可以把这段删了 orz

2023-02-20 23:09 UTC, bling-yshs commented on 启动器/LittleSkin 外置登录使用教程.xaml
>          <local:MyButton Margin="0,10,0,0" MinWidth="140" Padding="13,0" HorizontalAlignment="Left" Height="35" Text="打开网页版教程" EventType="打开网页" EventData="https://note.youdao.com/s/fHxFNnq" />
> @bling-yshs 看一看对着改改？ 其实我感觉没有必要这样，额外开一个网页也蛮复杂的……其实也可以把这段删了 orz

确实，这一段可以剪了。

2023-02-20 23:21 UTC, bling-yshs commented
@youzi-2333 这两张图片反了
![image](https://user-images.githubusercontent.com/41812674/220212032-ec63a4a9-1ccd-4e39-9351-4553e6102c05.png)

2023-02-21 12:58 UTC, youzi-2333 commented on 启动器/LittleSkin 外置登录使用教程.xaml
>          <local:MyButton Margin="0,10,0,0" MinWidth="140" Padding="13,0" HorizontalAlignment="Left" Height="35" Text="打开网页版教程" EventType="打开网页" EventData="https://note.youdao.com/s/fHxFNnq" />
主要是开一下帮助文档，开一下启动页面，确实挺烦的……

剪掉就剪掉吧.jpg

2023-02-21 13:01 UTC, youzi-2333 commented
按照要求改了一下，看看还有问题吗……
275135b

2023-02-21 19:17 UTC, LTCatt approved these changes

2023-02-21 19:17 UTC, merged