更新 安装 Mod 和 整合包安装 的表述和图片以适应 2.5.3 版本的更改
LTCatt/PCL2Help pull request #291
Opened 2023-04-09 12:23 UTC by WForst-Breeze

因为最近几个版本资源下载变化很大，这里再次更新一下有关内容

2023-04-09 14:13 UTC, LTCatt requested changes

2023-04-09 14:13 UTC, LTCatt commented on Minecraft/整合包安装.xaml
> +                        Text="3. 选择一个整合包。本教程使用 “RLCraft” 为范例。点击此整合包，点击您需要下载的版本，PCL2 会自动弹出输入版本名的窗口，您可自由输入，此处以 “RLCraft” 为范例，点击确定，PCL2 会自动开始下载。" HorizontalAlignment="Left" />
不要使用 “ 和 “，这会在 VS 里报错……

2023-04-10 12:59 UTC, WForst-Breeze commented
相关更改已完成

2023-04-10 16:10 UTC, LTCatt approved these changes

2023-04-10 16:10 UTC, merged