Update 存档损坏.xaml
LTCatt/PCL2Help pull request #292
Opened 2023-04-27 11:56 UTC by iPodtouch6557

有些地方其实有点难懂，并且我不敢保证所有人都不开版本隔离……
就怕某些人傻傻的死照着说明去做然后大叫 saves 文件夹里没有损坏存档，这个玩意没用

2023-04-27 12:02 UTC, iPodtouch6557 commented
忽然发现有个地儿没加空格……但是忘了咋修改了，谁教教我（）

2023-04-27 12:15 UTC, WForst-Breeze requested changes
有一些个人建议如下 😀

2023-04-27 12:15 UTC, WForst-Breeze commented on Minecraft/存档损坏.xaml
> +                    Text="1. 打开损坏存档所在的 .minecraft 文件夹，在对应版本的“版本设置” → “打开版本文件夹”后找到 saves 文件夹并进入。"/>
如果开启了版本隔离，那么应该打开的就不会是 .minecraft 文件夹，而是 versions 文件夹，此处会造成表达失误。可以依照新版本将此段落对应修改为 `1. 打开损坏存档的文件夹，在对应版本的 “版本设置” → “存档文件夹” 打开 saves 文件夹。`

2023-04-27 12:15 UTC, WForst-Breeze commented on Minecraft/存档损坏.xaml
> +                    Text="3. 找到“level.dat_old”，并在右键重命名时将后缀 “_old”部分删除。 "/>
在 -> 再；
可以把 “时” 换成逗号，会通顺点；
引号后面接个空格。

2023-04-27 12:15 UTC, WForst-Breeze commented on Minecraft/存档损坏.xaml
> +        <local:MyHint Text="如果没有显示后缀，请将显示文件扩展名打开即可 &#xA; Win7：资源管理器(我的电脑) → 组织 → 文件夹和搜索选项 → 查看 → 勾选“显示已知文件的扩展名” &#xA; Win10、Win11：资源管理器(此电脑) → 查看 → 勾选“文件扩展名” &#xA;如果损坏版本的版本隔离是生效的，那么你需要在 .minecraft/ve
同刚刚第一条，依照刚刚的步骤，使用者已经是可以顺利地打开 saves 文件夹的。个人认为这里就不必再强调了

2023-04-27 14:33 UTC, LTCatt approved these changes

2023-04-27 14:33 UTC, merged

2023-04-28 10:19 UTC, iPodtouch6557 commented
额…这个可以领活跃橙吗

2023-04-28 12:29 UTC, WForst-Breeze commented
> 额…这个可以领活跃橙吗

可以

2023-04-28 20:15 UTC, LTCatt commented
你的解锁码：pFymxuCb4wbkGOlNs/SIYO4CpkzvPLcT
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～