Delete 资源包安装.xaml
LTCatt/PCL2Help pull request #304
Opened 2023-06-23 13:11 UTC by liangbob2023

根据龙腾要求，删除了有关文件。

2023-06-23 18:26 UTC, LTCatt requested changes
我是说删掉 “资源包是什么?” 这张卡片，不是全删了啊哥

2023-06-24 06:28 UTC, liangbob2023 commented
@LTCatt 555我改我改我改。。。。

实在不好意思。。。

2023-06-24 08:26 UTC, LTCatt approved these changes

2023-06-24 08:27 UTC, merged

2023-06-24 13:08 UTC, liangbob2023 commented
@LTCatt 能给个活跃橙吗？

能的话，识别码：84E7-CB9B-3839-04D2

2023-06-24 20:24 UTC, LTCatt commented
你的解锁码：JT0stV/aECaP6IRvYzwGzMNeDN1n+to7
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～