添加PCL2为MSDerfender信任项的教程
LTCatt/PCL2Help pull request #305
Opened 2023-06-28 16:13 UTC by SuoHouDaiShi

添加PCL2为MSDerfender信任项的教程

2023-06-28 19:43 UTC, LTCatt requested changes
需要其他人修改格式，这个格式太悲伤了……

2023-06-29 09:23 UTC, SuoHouDaiShi commented
> 需要其他人修改格式，这个格式太悲伤了……

行，我去改改（）

2023-06-29 10:08 UTC, SuoHouDaiShi commented
> 需要其他人修改格式，这个格式太悲伤了……
完成了，您看看？

2023-06-29 10:13 UTC, SuoHouDaiShi commented
> 需要其他人修改格式，这个格式太悲伤了……

格式改好了，您看看？

2023-06-29 10:34 UTC, LTCatt commented
![image](https://github.com/LTCatt/PCL2Help/assets/40348278/6b067bdc-93b9-499e-9424-b4ae2077435c)

哥啊，求你看看吧……
内容质量太低了，标题都是错别字，我先关了如果谁打算重写再说吧……

2023-06-29 10:34 UTC, closed without merging

2023-06-29 13:37 UTC, WForst-Breeze commented
正好我也再打算写这样的一篇帮助文档，这里想问问是否有必要将这篇帮助文档设为仅快照版显示？毕竟考虑到发生静默删除 PCL2 的情况只出现在快照版