为存档损坏的修复教程添加了图文，更改了格式让它更符合规范
LTCatt/PCL2Help pull request #315
Opened 2023-07-29 13:51 UTC by HarukaB

2023-07-29 18:10 UTC, LTCatt requested changes

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +                    Text='1. 点击PCL2顶部的"启动"选项卡。'/>
用双引号，别用单引号

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +        <Image Margin="0,0,0,8" Source="https://statics.lvnya.top/pcl/broken_save/guide_versetting.webp"/>
别用什么 .webp，用 .png

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +                    Text="2. 点击对应版本的“版本设置” → “存档文件夹”后打开 saves 文件夹，图片示例:"/>
英文冒号？

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +                    Text="在电脑蓝屏、死机重启或异常关闭Minecraft等情况下,游戏存档可能会损坏,请按照以下步骤操作来尝试修复存档:"/>
英文前后的空格？用的英文逗号？

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +                    Text="2. 点击对应版本的“版本设置” → “存档文件夹”后打开 saves 文件夹，图片示例:"/>
图都放出来了还写”图片示例“干啥？根本没必要啊

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +                    Text='启动存档损坏的Minecraft版本,在主界面点击"单人游戏",在里面找到自己损坏的存档,找到世界标题下对应的文件夹名称,图片示例:'/>
单引号，缺空格，英文引号，英文冒号

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +        <local:MyCard Title="不知道如何找到自己的存档对应的文件夹?点击查看提示" Margin="0,0,0,15" CanSwap="True" IsSwaped="True">
英文问号？

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +        <local:MyHint Margin="0,0,10,4" Text="如果没有显示后缀名，请将文件的显示扩展名选项打开 &#xA; Win7：资源管理器(我的电脑) → 组织 → 文件夹和搜索选项 → 查看 → 勾选“显示已知文件的扩展名” &#xA; Win10：资源管理器(此电脑) → 查看 → 勾选“文件扩展名” &#xA; Win11: 资源管理器(此电脑) → 查
换行的行末加什么空格？

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +                    Text="此时将能正常游玩该存档，但需要注意的是：每次进入游戏都会自动备份存档为 level.dat_old 文件，所以使用此文档提供的恢复教程只能回档到上个未损坏的存档 。"/>
句号前面还有空格……

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +<local:MyCard Title="游戏存档损坏解决方案" Margin="0,0,0,15">
没必要啊，这个就是来看解决方案的，不用改

2023-07-29 18:10 UTC, LTCatt commented on Minecraft/存档损坏.xaml
> +        <local:MyHint Margin="0,0,10,4" Text="请注意,该教程使用Windows 11操作系统和Minecraft 1.20.1编写,可能不适用于所有版本,操作过程中的界面也可能有区别,请自己找到最适合自己的操作方式。" IsWarn="False"/>
别说废话，规范也错了

2023-07-29 18:11 UTC, LTCatt commented
算了算了，你这个 `更改了格式让它更符合规范` 结果一通瞎改比之前远远更不符合规范了……
如果有谁愿意重写可以继续重写，但这个 Pull Request 我不会收，质量太差了……抱歉 :/

2023-07-29 18:11 UTC, closed without merging

2023-07-29 21:24 UTC, HarukaB commented
实在是不好意思，第一次编辑Xml格式的帮助看得头晕，我会再次仔细检查一遍并修改不合适的部分再来考虑PR的

2023-07-29 21:31 UTC, HarukaB commented
另外还有一个问题，规范里写"考虑到面对的受众，则应该写的尽量详细"，所以我加了很多图片，有必要吗？

2023-07-30 03:10 UTC, WForst-Breeze commented
> 另外还有一个问题，规范里写"考虑到面对的受众，则应该写的尽量详细"，所以我加了很多图片，有必要吗？

个人认为，考虑到此页面的受众范围，是有必要的，但是一些步骤操作可以合并为一个步骤，一张图也可以同时展示一个步骤的多步操作，这样会更好一些~