完善 加入服务器 页面
LTCatt/PCL2Help pull request #317
Opened 2023-07-31 14:21 UTC by youzi-2333

加了两个报错：`Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException` `此服务器未启用飞行`，来源于 PCL x9 群……

另外就是网站尽可能地不使用 GitHub，然后让语言看上去更加的……额……书面化（

2023-07-31 18:28 UTC, LTCatt requested changes

2023-07-31 18:28 UTC, LTCatt commented on Minecraft/加入服务器.xaml
>  </local:MyCard>
这个属于不常见报错，没必要加进去

2023-07-31 23:25 UTC, youzi-2333 commented on Minecraft/加入服务器.xaml
>  </local:MyCard>
ok 改好了 √
09f99ea

2023-08-01 02:52 UTC, youzi-2333 commented
14a1501 由于 PCL 帮助文档的图片疑似全部爆炸，已经把我图床账号下的所有帮助图片翻新。

2023-08-01 03:01 UTC, z0z0r4 commented
> [14a1501](https://github.com/LTCatt/PCL2Help/commit/14a15017eee979fc4d97374f2a843daf60ec157b) 由于 PCL 帮助文档的图片疑似全部爆炸，已经把我图床账号下的所有帮助图片翻新。

这是事故，原因未知，在找

2023-08-01 06:50 UTC, LTCatt approved these changes

2023-08-01 06:50 UTC, merged