Intellij Idea关于提交的帮助教程
LTCatt/PCL2Help pull request #323
Opened 2023-08-16 11:29 UTC by Ian-Rin

是根据上面哥们的文件，去除了不能运行的部分。

2023-08-16 14:23 UTC, WForst-Breeze reviewed
需要根据帮助库编写规范重新进行排版规范化及措辞调整qwq（如 空格、标点、箭头符号等）

2023-08-17 14:43 UTC, WForst-Breeze requested changes
帮忙简单找了点格式上的错误，其它排版和措辞没有找，麻烦再自行调整调整qwq 如果有误再沟通——！

2023-08-17 14:43 UTC, WForst-Breeze commented on 帮助/提交帮助 - Intellij Idea.xaml
> +<local:MyHint Margin="0,0,0,15" Text="该帮助页面还需要根据规范重新整理格式，优化排版与文案。如果你感兴趣也可以来帮帮忙！, 以VSCode教程和Git教程为模板" IsWarn="False" />
删除 `, 以VSCode教程和Git教程为模板`，在此处不必说明

2023-08-17 14:43 UTC, WForst-Breeze commented on 帮助/提交帮助 - Intellij Idea.xaml
> +                    Text="1. 安装 Git Integration 插件。首先打开 IntelliJ IDEA，然后依次点击“File”-->“Settings”-->“Plugins”，在出现的搜索框内输入“Git Integration”，找到插件并进行安装。" />
箭头：→，引号外添加空格（引号与逗号间无需添加空格）

2023-08-17 14:43 UTC, WForst-Breeze commented on 帮助/提交帮助 - Intellij Idea.xaml
> +        <TextBlock Margin="0,0,0,4" LineHeight="17" Text="3. 将 SSH 公钥添加到 GitHub。点击下面的“访问设置”按钮，然后在 GitHub 设置页面点击 'SSH and GPG keys'，接着点击 'New SSH Key'，最后在 'Key' 区域粘贴步骤2中复制的 SSH 公钥，并为其添加标题。" />
引号空格，使用双引号

2023-08-17 14:43 UTC, WForst-Breeze commented on 帮助/提交帮助 - Intellij Idea.xaml
> +          <TextBlock Margin="0,5,0,4" LineHeight="17" Text="4. 在 Terminal 中设置 Git 用户信息，需确保 Git 邮箱和 SSH 公钥使用的是相同的邮箱。如果只对当前库设置用户信息，`--global` 参数可以省略。" />
使用双引号而不是反引号

2023-08-17 14:43 UTC, WForst-Breeze commented on 帮助/提交帮助 - Intellij Idea.xaml
> +        <TextBlock Margin="0,5,0,4" LineHeight="17" Text="1. 克隆仓库到本地。打开 Terminal，输入git clone https://github.com/LTCatt/PCL2Help.git，此操作会在本地创建一个名为 'PCL2Help' 的文件夹，并将代码仓库的内容下载到这个文件夹。" />
英文与中文间空格，双引号

2023-08-17 14:43 UTC, WForst-Breeze commented on 帮助/提交帮助 - Intellij Idea.xaml
> +        <TextBlock Margin="0,5,0,4" LineHeight="17" Text="2. 使用 IntelliJ IDEA 进行编写。首先，在 Terminal 中输入 cd PCL2Help 切换到代码仓库目录，然后打开 IntelliJ IDEA，选择打开已有的项目，选择刚刚下载的 'PCL2Help' 文件夹，编写代码并保存更改。" />
单引号改为双引号，`“cd PCL2Help”`

2023-08-17 14:43 UTC, WForst-Breeze commented on 帮助/提交帮助 - Intellij Idea.xaml
> +         <TextBlock Margin="0,5,0,4" LineHeight="17" Text="在 GitHub 源代码仓库页面创建新的 Pull Request。点击下方的'新建 Pull Request'按钮，填写标题和描述，然后提交。在创建 Pull Request 之前，请确保你的分支与源仓库是同步的。" />
双引号，空格

2023-08-17 14:43 UTC, WForst-Breeze commented on 帮助/提交帮助 - Intellij Idea.xaml
> +         <TextBlock Margin="0,5,0,4" LineHeight="17" Text="若需同步源仓库和你的分支，打开你的 Fork 仓库页面，点击 'Fetch upstream'，然后点击 'Fetch and merge'。" />
双引号

2023-08-17 15:14 UTC, Ian-Rin commented
感谢指正，已修改

2023-08-17 18:21 UTC, LTCatt requested changes

2023-08-17 18:21 UTC, LTCatt commented on 帮助/提交帮助 - Intellij Idea.xaml
> +                    Text="1. 安装 Git Integration 插件。首先打开 IntelliJ IDEA，然后依次点击“File”→“Settings”→“Plugins”，在出现的搜索框内输入”Git Integration“，找到插件并进行安装。" />
双引号问题

2023-08-17 18:21 UTC, LTCatt commented on 帮助/提交帮助 - Intellij Idea.xaml
> +                    Text="2. 生成 SSH 公钥和私钥。打开 “Terminal”，并输入 “ssh-keygen -t rsa -C ”你的邮箱' ” 以生成 SSH 公钥和私钥，然后打开生成的 id_rsa.pub 文件，并复制文件中的内容。" />
同样引号不规范

2023-08-17 18:21 UTC, LTCatt commented on 帮助/提交帮助 - Intellij Idea.xaml
> +                    Text="3. 将 SSH 公钥添加到 GitHub。点击下面的 “访问设置” 按钮，然后在 GitHub 设置页面点击 “SSH and GPG keys”，接着点击 “New SSH Key”，最后在 'Key' 区域粘贴步骤2中复制的 SSH 公钥，并为其添加标题。" />
Key 为啥就是单引号了……

2023-08-17 18:21 UTC, LTCatt commented on 帮助/提交帮助 - Intellij Idea.xaml
> +<local:MyCard Title="利用 Git 获取代码库并进行版本控制">
没必要写 “并进行版本控制”

2023-08-17 18:21 UTC, LTCatt commented on 帮助/提交帮助 - Intellij Idea.xaml
> +        <TextBlock Margin="0,5,0,4" LineHeight="17" Text="1. 克隆仓库到本地。打开 ”Terminal“，输入git clone https://github.com/LTCatt/PCL2Help.git，此操作会在本地创建一个名为 “PCL2Help” 的文件夹，并将代码仓库的内容下载到这个文件夹。" />
引号又反了……

2023-08-17 18:21 UTC, LTCatt commented on 帮助/提交帮助 - Intellij Idea.xaml
> +<local:MyHint Margin="0,0,0,15" Text="该帮助页面还需要根据规范重新整理格式，优化排版与文案。如果你感兴趣也可以来帮帮忙！" IsWarn="False" />
全部改完可以把这个删了

2023-08-18 04:03 UTC, Ian-Rin commented
已根据要求修正

2023-08-18 04:44 UTC, LTCatt approved these changes

2023-08-18 04:44 UTC, merged

2023-08-18 14:39 UTC, LTCatt commented
你的解锁码：3meUIa30Reg68IR85nuv8WSvG4wfH33U
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

2025-04-01 08:15 UTC, Ian-Rin commented
能不能帮我的新电脑解锁一下主题，我的新识别码是：7896-4013-F66E-70CD

2025-04-01 09:22 UTC, LTCatt commented
你这识别码没变啊，用上面那个就行

2025-04-01 14:20 UTC, Ian-Rin commented
刚刚在旧电脑弄资料，复制错了

2025-04-01 21:32 UTC, LTCatt commented
你的解锁码：ExvsnnN3XmOdnaSUktY73lzxU2RpaQE2
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～