规范化并优化 Mod 安装 页面
LTCatt/PCL2Help pull request #326
Opened 2023-08-27 15:04 UTC by WForst-Breeze

## 前言
最近时间比较紧，十几分钟赶出来的，改动比较大，但能检查到的都检查到了，但疏漏估计还是有的，还请指出啦——！谢谢

## 内容
- 于 xaml 文件开首处添加图片备份连接
- 将 MyCard 中的 “ - ” 统一修改为括号以保证页面整齐
- 重制 安装 Mod 加载器 部分，修改操作步骤图片以统一风格符合规范
- 重排版并修正措辞 下载并安装 Mod（Mod 文件）部分，修改操作步骤图片以统一风格符合规范
- 合并部分 MyHint，尽可能减少 MyHint 数量使得页面整洁

2023-08-28 10:54 UTC, LTCatt requested changes

2023-08-28 10:54 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +                        Text="2. 在弹出的菜单中点击 &quot;打开 Mod 文件夹&quot; 以打开选定游戏版本的 mods 文件夹。" HorizontalAlignment="Left" />
“点击打开 Mod 文件夹以打开选定游戏版本的 mods 文件夹”这句有点啰嗦了，可以精简一点 =。=

2023-08-28 10:54 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +		<TextBlock TextWrapping="Wrap" Margin="0,0,0,4" LineHeight="17" Text="若仅需要安装单个模组，可以在版本设置中选择需要安装 Mod 的版本后，直接将该 Mod 文件拖入 PCL 窗口进行安装。若需要批量安装 Mod，请依照以下步骤进行安装：" />
批量安装 mod 也可以拖，我估计后面这一段教程实际上都不需要？

2023-08-28 14:53 UTC, WForst-Breeze commented on Minecraft/安装 Mod.xaml
> +		<TextBlock TextWrapping="Wrap" Margin="0,0,0,4" LineHeight="17" Text="若仅需要安装单个模组，可以在版本设置中选择需要安装 Mod 的版本后，直接将该 Mod 文件拖入 PCL 窗口进行安装。若需要批量安装 Mod，请依照以下步骤进行安装：" />
如果是一次性安装单个模组出问题了可以直接在 PCL2 里禁用，但批量装 Mod 出问题了后期的一些调试还是在 mods 文件夹操作方便点（）我可以修改一下表述，但我个人认为那段教程还是有必要的

2023-08-28 16:43 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +		<TextBlock TextWrapping="Wrap" Margin="0,0,0,4" LineHeight="17" Text="若仅需要安装单个模组，可以在版本设置中选择需要安装 Mod 的版本后，直接将该 Mod 文件拖入 PCL 窗口进行安装。若需要批量安装 Mod，请依照以下步骤进行安装：" />
我觉得单就主题 “安装 Mod” 而言，直接教拖入更加简单明了，没有必要把它复杂化——需要看这个帮助的绝对是新人，当然用最简单的方式就好。
如果安装出问题了之类的其实可以单开一个帮助条目……

2023-08-30 05:34 UTC, WForst-Breeze commented on Minecraft/安装 Mod.xaml
> +		<TextBlock TextWrapping="Wrap" Margin="0,0,0,4" LineHeight="17" Text="若仅需要安装单个模组，可以在版本设置中选择需要安装 Mod 的版本后，直接将该 Mod 文件拖入 PCL 窗口进行安装。若需要批量安装 Mod，请依照以下步骤进行安装：" />
Mod 出现问题很难做成帮助文件，因为其涉及的类型太多了（）参考 [GlobeMC/crashmc.com](https://github.com/GlobeMC/crashmc.com)

考虑了一下现在 PCL2 支持批量管理 Mod 了，我就先把下面的教程先隐藏了。

不过我个人仍然建议保留此段教程，毕竟新人安装 Mod，这种是最稳妥的、最不易出错的方式，我个人认为我们不能单考虑 “安装 Mod” 这一操作，也要考虑怎么样才能让看这篇教程的人照做后出错率最低qwq……

2023-08-30 06:30 UTC, LTCatt approved these changes

2023-08-30 06:31 UTC, merged