规范化帮助库页面
LTCatt/PCL2Help pull request #336
Opened 2023-11-05 11:49 UTC by WForst-Breeze

### 前言
主要针对整合包安装、皮肤导出、光影安装页面进行了修改，对光影页面进行了全文重排版和重新措辞。做得比较赶，问题肯定超多，可能只能下周末才能解决出现的问题，抱歉orz！

### 内容
- 重写整合包安装页面中的 “安装已有压缩文件” 部分
- 帮助库图片规范中添加一条
- 导出皮肤页面中的 MyCard 默认折叠
- 大篇幅修改安装光影页面内容，重新排版并细化操作步骤、删减冗余内容。

2023-11-06 08:25 UTC, LTCatt requested changes

2023-11-06 08:25 UTC, LTCatt commented on Minecraft/安装光影.xaml
> +                   Text="目前提供光影功能的 Mod 有 OptiFine 和 Iris Shaders。其中 Optifine 支持 Forge 加载器（可以通过 OptiFabric Mod 兼容 Fabric），Iris Shaders 支持 Fabric 和 Quilt 加载器。" />
Optifine 的 F 大写；没必要强调“加载器”（简洁考量）

2023-11-06 08:25 UTC, LTCatt commented on Minecraft/安装光影.xaml
> +                   Text="Iris Shaders 支持的游戏版本较少，但其支持的 Sodium Mod 对图像性能的优化效果显著且兼容性较好，其表现在较高版本通常优于 OptiFine。因此对于 1.16 及以上版本，推荐使用 Iris Shaders。" />
umm 帮助库最好还是保持中立，不要有推荐性质的内容

2023-11-06 08:25 UTC, LTCatt commented on Minecraft/安装光影.xaml
> +                   Text="光影包和资源包类似，是由 Minecraft 玩家创作并分享的，你可以在网上找到其他玩家制作的光影包。很多 Minecraft 交流网站（如 MCBBS）都有专门的光影版块，你可以在这些地方挑选自己喜欢的光影包。OptiFine 也提供了一个分享光影包的网站，在光影设置界面点击光影包文件夹旁的下载按钮即可。" />
语句有点废话了，精简一下？

2023-11-06 08:25 UTC, LTCatt commented on Minecraft/安装光影.xaml
> +        <local:MyHint Margin="0,4,0,0" Text="若您需要在 Fabric 加载器下加载 Optifine，直接在自动安装页面选择你想要安装的 Fabric 版本即可，PCL 会自动为你选择安装合适的 Fabric API 和 OptiFabric。" IsWarn="False" />
Fabric 加载器 → Fabric
Optifine → OptiFine

2023-11-06 09:12 UTC, WForst-Breeze commented on Minecraft/安装光影.xaml
> +                   Text="Iris Shaders 支持的游戏版本较少，但其支持的 Sodium Mod 对图像性能的优化效果显著且兼容性较好，其表现在较高版本通常优于 OptiFine。因此对于 1.16 及以上版本，推荐使用 Iris Shaders。" />
但一定程度的推荐还是有必要的，毕竟面对的是新手🤔如果就是直接说 1.16- 推荐用 OptiFine 1.16+ 推荐用 Iris 可以吗

2023-11-06 13:14 UTC, LTCatt requested changes

2023-11-06 13:14 UTC, LTCatt commented on Minecraft/安装光影.xaml
> +                   Text="综合考量，对于 1.16 以下版本，推荐使用 OptiFine；而对于 1.16 及以上版本，推荐使用 Iris Shaders。" />
我的意思是就不加这种推荐语句了 =。=

2023-11-07 17:00 UTC, LTCatt requested changes

2023-11-07 17:00 UTC, LTCatt commented on Minecraft/整合包安装.xaml
> +
已在 Hex-Dragon/PCL2#2531 修复

2023-11-11 14:19 UTC, deep-dark-forest commented
好耶!
墙裂建议加入mc服务器列表按钮，这样也许能给孤独的新玩家提供一些帮助。。？
链接是：findmcserver.com
![8915216997122212.png](https://github.com/LTCatt/PCL2Help/assets/131975043/061ae6db-2cd1-43f2-b013-923d5d71a3fa)
图片来自于https://b23.tv/nsIIEdw

2023-11-11 15:49 UTC, WForst-Breeze commented on Minecraft/整合包安装.xaml
> +
![image](https://github.com/LTCatt/PCL2Help/assets/110760354/a7607b3a-5519-4fe4-a4ec-a733bd505c4d)

2023-11-14 14:03 UTC, WForst-Breeze commented on Minecraft/整合包安装.xaml
> +
尝试过了还是不行，reopen了。当时写的时候就是测试了一下不行，又去更新日志里找这一条也没找到才把这段话写上去的（

2023-11-16 10:14 UTC, LTCatt approved these changes

2023-11-16 10:14 UTC, merged