规范化帮助库页面（安装世界、资源包安装、存档损坏）
LTCatt/PCL2Help pull request #343
Opened 2023-12-11 13:30 UTC by WForst-Breeze

### 前言
主要针对安装世界、安装资源包、存档损坏解决方案页面进行规范化。

### 更改
重写安装世界页面，去除安装资源包页面冗余表述，扩充存档损坏步骤图片并重排版该页面。

###### 高烧之作……问题肯定不少，多多包容啦~！TwT

2023-12-11 14:01 UTC, LTCatt requested changes

2023-12-11 14:01 UTC, LTCatt commented on Minecraft/安装世界.xaml
> +		           EventType="打开帮助" EventData="Minecraft/资源包安装.json" />
感觉这个其实没必要教，对还需要看这个教程的新玩家而言这个很少用到，但会让他们更头疼

2023-12-11 14:01 UTC, LTCatt commented on Minecraft/资源包安装.xaml
> +                   Text="4. 最后，等待 Mojang 进度条至尽头，资源包即可加载完成。"/>
没必要加这句

2023-12-12 09:46 UTC, LTCatt commented on Minecraft/安装世界.xaml
>  </local:MyCard>
是，可以默认点进来“如何安装整合包”的玩家知道整合包是啥……其余同理

2023-12-14 07:03 UTC, WForst-Breeze commented on Minecraft/安装世界.xaml
> +		           EventType="打开帮助" EventData="Minecraft/资源包安装.json" />
![image](https://github.com/LTCatt/PCL2Help/assets/110760354/248c16d0-6f95-433a-83d3-190393af6a9b)
那这个有必要保留吗，我先把排版改一下，如果没必要我也一起删了🤔

2023-12-14 08:09 UTC, LTCatt approved these changes

2023-12-14 08:09 UTC, merged