修改 “提交帮助 - GitHub Desktop” 部分
LTCatt/PCL2Help pull request #365
Opened 2024-05-12 14:56 UTC by wuyuncheng-26

第 8 行：
原链接 `https://docs.github.com/cn/desktop/installing-and-configuring-github-desktop/getting-started-with-github-desktop#part-1-installing-and-authenticating`
会被重定向至 `https://docs.github.com/zh/desktop/overview/getting-started-with-github-desktop#part-1-installing-and-authenticating`
其他的是一些符号问题

2024-05-12 21:41 UTC, LTCatt requested changes

2024-05-12 21:41 UTC, LTCatt commented on 帮助/提交帮助 - GitHub Desktop.json
> +    "__Author__": "Not_Killer_233、龙腾猫跃、XiaoFans、wuyuncheng-26",
为啥还加了 XiaoFans？
此外，编修级别的小更改不要把自己加进 author

2024-05-13 10:50 UTC, wuyuncheng-26 commented on 帮助/提交帮助 - GitHub Desktop.json
> +    "__Author__": "Not_Killer_233、龙腾猫跃、XiaoFans、wuyuncheng-26",
XiaoFans 是在 XAML 里面，没添加到 JSON 里

2024-05-13 10:50 UTC, wuyuncheng-26 commented on 帮助/提交帮助 - GitHub Desktop.json
> +    "__Author__": "Not_Killer_233、龙腾猫跃、XiaoFans、wuyuncheng-26",
Author我待会改改

2024-05-13 10:53 UTC, wuyuncheng-26 commented
ok了

2024-05-13 12:25 UTC, LTCatt approved these changes

2024-05-13 12:25 UTC, merged