添加 java 下载以及一点点修改
LTCatt/PCL2Help pull request #376
Opened 2024-06-13 13:41 UTC by Fish-LP

我朋友竟然找不到java11(

2024-06-13 13:46 UTC, allMagicNB commented
时效性太强

2024-06-13 13:56 UTC, Fish-LP commented
是这里的https://adoptium.net/zh-CN/
pcl不能自动下载旧版java吧(应该?)

2024-06-13 13:57 UTC, allMagicNB commented
> 是这里的https://adoptium.net/zh-CN/
> pcl不能自动下载旧版java吧(应该?)

你要不要先试试

2024-06-13 18:00 UTC, LTCatt requested changes
“一点点修改”的那一部分没问题，可以留着。
添加 Java 下载……这个真的没必要。现在有自带的 Java 补全，可以应对大多数情况了。帮助库的核心目的还是为了服务小白玩家……这个还是删了吧 Orz。

2024-06-14 07:25 UTC, Fish-LP commented
留个java11吧，有的包需要，但是小白不会(比如我朋友)

2024-06-14 09:00 UTC, LTCatt commented
“我有一个朋友需要” 也不能说明这是 ”小白普遍存在的，以至于需要加入帮助库“ 的问题 :/

2024-06-14 11:09 UTC, Fish-LP commented
改好了我该怎么做 :|

2024-06-14 11:12 UTC, allMagicNB requested changes

2024-06-14 11:12 UTC, allMagicNB commented on 帮助/提交帮助 - 编写规范.xaml
> +                    Text="  3. 你的条目需要适用于较多玩家，且有足够派上用场的可能。如果它面向的情景极少发生或者具有时效性，那就不要添加它。" />
```suggestion
                    Text="  3. 你的条目需要适用于较多玩家，且有足够派上用场的可能。如果它面向的情景极少发生或者具有很强的时效性，那就不要添加它。" />
```

2024-06-14 11:12 UTC, allMagicNB commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。"/>
这段感觉还得改改，别直接删……

2024-06-14 11:27 UTC, Fish-LP commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。"/>
改了 : )

2024-06-14 12:02 UTC, LTCatt requested changes

2024-06-14 12:02 UTC, LTCatt commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中，在查看 → 显示下方选中 ”隐藏的项目“ 查看 .git 文件夹是否存在于 Help 文件夹"/>
双引号反了，结尾没有句号

2024-06-14 12:02 UTC, LTCatt commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中，在查看 → 显示下方选中 ”隐藏的项目“ 查看 .git 文件夹是否存在于 Help 文件夹"/>
`此外你可以选择在资源管理器中，在查看 → 显示下方选中 ”隐藏的项目“ 查看 .git 文件夹是否存在于 Help 文件夹`
这句话太绕口了……

2024-06-14 12:25 UTC, Fish-LP commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中，在查看 → 显示下方选中 ”隐藏的项目“ 查看 .git 文件夹是否存在于 Help 文件夹"/>
改了(怎么引用代码段的啊)

2024-06-14 18:34 UTC, LTCatt requested changes
此外，你可以选择在资源管理器中打开 选项卡查看 → 显示/隐藏 中的 “隐藏的项目”，以查看 .git 文件夹存在于 Help 文件夹内

2024-06-14 18:34 UTC, LTCatt commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中打开 选项卡查看 → 显示/隐藏 中的 “隐藏的项目”选项 以查看 .git 文件夹是否存在于 Help 文件夹内"/>
`之后，将第二步中 clone 的仓库内 PCL2Help 的文件夹剪切到 PCL 目录下，并将 PCL2Help 文件夹重命名为 Help。`
这一段感觉只需要改成这句话就行了，后面那句查看 .git 的都感觉是多余的？

2024-06-14 22:45 UTC, Fish-LP commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中打开 选项卡查看 → 显示/隐藏 中的 “隐藏的项目”选项 以查看 .git 文件夹是否存在于 Help 文件夹内"/>
我不知道.git是干嘛的()不确定重要性

2024-06-14 23:21 UTC, allMagicNB commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中打开 选项卡查看 → 显示/隐藏 中的 “隐藏的项目”选项 以查看 .git 文件夹是否存在于 Help 文件夹内"/>
配置 git 的……

2024-06-14 23:31 UTC, Fish-LP commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中打开 选项卡查看 → 显示/隐藏 中的 “隐藏的项目”选项 以查看 .git 文件夹是否存在于 Help 文件夹内"/>
一般不用管吗

2024-06-14 23:34 UTC, Fish-LP commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中打开 选项卡查看 → 显示/隐藏 中的 “隐藏的项目”选项 以查看 .git 文件夹是否存在于 Help 文件夹内"/>
.开头的文件默认隐藏 小白会觉得缺少文件吗

2024-06-15 08:26 UTC, LTCatt commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中打开 选项卡查看 → 显示/隐藏 中的 “隐藏的项目”选项 以查看 .git 文件夹是否存在于 Help 文件夹内"/>
这部分不需要用户操作，只要正确的剪切、重命名，这里就不会出问题，所以这句话都可以删了……
我个人是觉得把这一段直接换成 `之后，将第二步中 clone 的仓库内 PCL2Help 的文件夹剪切到 PCL 目录下，并将 PCL2Help 文件夹重命名为 Help。` 就行

2024-06-15 08:54 UTC, Fish-LP commented on 帮助/提交帮助 - VSCode.xaml
> +                    Text="完成上述后，将第二步 clone 下仓库内 PCL2Help 文件夹剪切到 PCL 目录下并重命名文件夹 PCL2Help 为 Help 。此外你可以选择在资源管理器中打开 选项卡查看 → 显示/隐藏 中的 “隐藏的项目”选项 以查看 .git 文件夹是否存在于 Help 文件夹内"/>
ok，主要是我也不了解。

2024-06-15 10:01 UTC, LTCatt approved these changes

2024-06-15 10:01 UTC, merged

2024-06-16 04:06 UTC, Fish-LP commented
6D64-BB4A-F5A4-AB8A

2024-06-16 08:52 UTC, LTCatt commented
你的解锁码：Z+r1XUPeoXqFAPN5YjG9oSrnZelFWIVR
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～

2024-11-07 12:36 UTC, Fish-LP commented
853B-F3C1-43C6-D933

2024-11-07 12:51 UTC, LTCatt commented
你的解锁码：Ljog3QeVZjXDcDfUuH7WcQ0nY/6O3K6q
在 更多 → 关于与鸣谢 → 输入解锁码 中使用，谢谢支持～