- 增加账户被禁用的另一种可能
LTCatt/PCL2Help pull request #385
Opened 2024-07-28 05:42 UTC by Enigma-Soul

好了，我保证，Bug都没了
![image](https://github.com/user-attachments/assets/e8b51755-a0f7-4503-9988-19536cc22970)
![image](https://github.com/user-attachments/assets/1196248a-58b3-4cff-bcb7-d63eca92f61e)

2024-07-28 08:08 UTC, LTCatt requested changes

2024-07-28 08:08 UTC, LTCatt commented on Minecraft/加入服务器.xaml
> +                          EventType="打开网页" EventData ="https://account.microsoft.com/profile" Type="Clickable" />
如果你的 MyListItem 没有 Logo，还不如换用 MyButton。
边距太宽了……

2024-07-28 09:16 UTC, Enigma-Soul commented
OK

2024-07-28 10:34 UTC, Enigma-Soul commented on Minecraft/加入服务器.xaml
> +                          EventType="打开网页" EventData ="https://account.microsoft.com/profile" Type="Clickable" />
等下，我那Logo删掉的原因是PCL无法加载microsoft网站的Logo，所以把Logo设置为空，如果把Logo换成一个空白图标会不会更好些

2024-07-28 11:37 UTC, allMagicNB commented on Minecraft/加入服务器.xaml
> +                          EventType="打开网页" EventData ="https://account.microsoft.com/profile" Type="Clickable" />
Minecraft 官网有鉴权。

2024-07-28 11:48 UTC, LTCatt commented on Minecraft/加入服务器.xaml
> +                          EventType="打开网页" EventData ="https://account.microsoft.com/profile" Type="Clickable" />
你这里也不需要用 MyListItem 啊……

2024-07-28 14:30 UTC, Enigma-Soul commented on Minecraft/加入服务器.xaml
> +                          EventType="打开网页" EventData ="https://account.microsoft.com/profile" Type="Clickable" />
…

2024-07-28 16:11 UTC, Enigma-Soul commented on Minecraft/加入服务器.xaml
> +                          EventType="打开网页" EventData ="https://account.microsoft.com/profile" Type="Clickable" />
说实话，主要是好看，有空可以把Icon文件放在图片托管网站上,比 `MyButton`好看

2024-07-28 18:11 UTC, LTCatt commented on Minecraft/加入服务器.xaml
> +                          EventType="打开网页" EventData ="https://account.microsoft.com/profile" Type="Clickable" />
但没有需要的话就应当不用它，改成 MyButton 吧 =。=

2024-07-29 14:07 UTC, WForst-Breeze commented on Minecraft/加入服务器.xaml
> +</local:MyCard>
重写了一下，会不会好一点？
![1722262019303](https://github.com/user-attachments/assets/42dcbf45-4a4f-47f1-b111-dad6d4d40cb4)


```suggestion
    <StackPanel Margin="25,40,23,11">
        <TextBlock Margin="0,5,0,0" FontSize="16" Foreground="{DynamicResource ColorBrush2}"
                   Text="正版账户" />
        <local:MyHint Margin="0,10,0,10" Text="如果你是 Microsoft 家庭中的一员，请进入 Microsoft 家庭设置查看家庭管理者，并用家庭管理者的账号更改年龄。" IsWarn="False" />
        <TextBlock Margin="0,0,0,4" LineHeight="17"
                    Text="解决方法：点击下方按钮进入 Microsoft 账户信息设置，并更改个人资料中的年龄，使其大于 18 周岁。再进入 Xbox 隐私和在线安全，选择 Xbox 与 Windows 10 设备在线安全，把 “You can join cross-network play” 设置为 “允许”。" />
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Left">
            <local:MyButton Margin="0,4,20,0" Height="35" HorizontalAlignment="Left" Padding="13,0,13,0"
                        Text="Microsoft 账户信息设置" EventType="打开网页" EventData="https://account.microsoft.com/profile" />
            <local:MyButton Margin="0,4,20,0" Height="35" HorizontalAlignment="Left" Padding="13,0,13,0"
                        Text="Xbox 隐私和在线安全" EventType="打开网页" EventData="https://www.xbox.com/zh-CN/user/settings/privacy-and-safety" />
            <local:MyButton Margin="0,4,20,00" Height="35" HorizontalAlignment="Left" Padding="13,0,13,0"
                        Text="Microsoft 家庭设置" EventType="打开网页" EventData="https://account.microsoft.com/family/home" />
		</StackPanel>
        
        <TextBlock Margin="0,20,0,12" FontSize="16" Foreground="{DynamicResource ColorBrush2}"
                   Text="离线账户" />
            <TextBlock Margin="0,0,0,4" LineHeight="17"
                    Text="原因：目前离线账户无法使用 1.16.4 和 1.16.5 的多人游戏功能。" />
            <TextBlock Margin="0,0,0,4" LineHeight="17"
                    Text="解决方法：请逐一尝试以下方法。" />
            <TextBlock Margin="2,0,0,4" LineHeight="17"
                    Text="1. 使用正版登录或第三方登录进入游戏。" />
            <TextBlock Margin="2,0,0,4" LineHeight="17"
                    Text="2. 尝试在启动游戏时断开网络连接。" />
            <TextBlock Margin="2,0,0,4" LineHeight="17"
                    Text="3. 安装下方的 “离线多人修正” 或 “Offline Multiplayer” 模组。" />
            <local:MyListItem  Margin="0,0,0,4"
		            Title="离线多人修正 | MultiOfflineFix" Info="Fabric / Forge 1.16.4 - 1.16.5"
		            EventType="打开网页" EventData="https://www.mcmod.cn/download/10643.html" Type="Clickable" />
            <local:MyListItem  Margin="0,0,0,4"
                    Title="Offline Multiplayer" Info="Fabric 1.16.5"
                    EventType="打开网页" EventData="https://github.com/ChickenPige0n/offline-multiplayer-fabric/releases" Type="Clickable" />
            <!--MCBBS 已关停，此处链接已失效 
            <TextBlock Margin="2,2,0,4" LineHeight="17"
                    Text="4. 使用下方的 Authlib 更新工具。" />
            <local:MyListItem  Margin="0,0,0,4"
                    Title="Authlib 更新工具" Info="502mc 制作的 Authlib 更新工具，支持修复未安装 Mod 加载器的客户端。"
                    EventType="打开网页" EventData="https://www.mcbbs.net/thread-1450892-1-1.html" Type="Clickable" />
            -->
    </StackPanel>
</local:MyCard>
```

2024-07-30 09:30 UTC, Enigma-Soul commented on Minecraft/加入服务器.xaml
> +</local:MyCard>
可以，挺好

2024-07-30 15:09 UTC, LTCatt approved these changes

2024-07-30 15:10 UTC, LTCatt commented
两个 mod 链接的 MyListItem 可以用内建的命令方块图标 =。=

2024-07-30 23:45 UTC, Enigma-Soul commented
> 两个 mod 链接的 MyListItem 可以用内建的命令方块图标 =。=

..............................................................................................................................

2024-07-31 02:09 UTC, WForst-Breeze commented
> ..............................................................................................................................

没事，你要是不想改直接合并了之后我再开一个 pr 改也可以的……

2024-08-01 11:24 UTC, Enigma-Soul commented
PR提了一个月了(Doge

2024-08-11 12:28 UTC, LTCatt commented
> 两个 mod 链接的 MyListItem 可以用内建的命令方块图标 =。=

.

2024-08-12 11:02 UTC, Enigma-Soul commented
虽然不是我们做的，但我还是可以帮你把它改一改

2024-08-12 11:10 UTC, Enigma-Soul commented
e...名字没改，
![image](https://github.com/user-attachments/assets/f5a21014-63ad-49eb-8842-448a2bf13b0a)

2024-08-12 17:57 UTC, LTCatt approved these changes

2024-08-12 17:57 UTC, merged