增加了皮肤导出的详尽教程
LTCatt/PCL2Help pull request #50
Opened 2021-06-26 00:34 UTC by DreamUniverse843

如题。
教程路径为 \启动器\如何导出角色的皮肤.xaml

2021-07-08 08:30 UTC, LTCatt requested changes

2021-07-08 08:30 UTC, LTCatt commented on Minecraft/设置分配内存大小.json
> +	"Description": "为 Minecraft 手动设置游戏内存大小，在自动分配内存出错时使用",
“自动分配内存出错”……这个不会出错只会效果不佳，建议用原表述

2021-07-08 08:30 UTC, LTCatt commented on Minecraft/设置分配内存大小.json
> +	"Types": ["启动器"]
它与 Minecraft 相关，建议保留 Minecraft 类别

2021-07-08 08:30 UTC, LTCatt commented on 启动器/如何导出角色的皮肤.xaml
> +		<local:MyHint Margin="0,-5,0,15" Text="由于 PCL 2 内置了正版皮肤导出，我们建议您使用此方法更快速地导出。&#xa;当然，前述的方式 1 同样适用于正版用户。"/>
只保留方法 1 即可。

2021-07-08 14:13 UTC, DreamUniverse843 commented
谢谢您审阅，上述三个问题已修正。

2021-07-13 09:37 UTC, LTCatt approved these changes

2021-07-13 09:38 UTC, merged