增加“导入存档”教程
LTCatt/PCL2Help pull request #52
Opened 2021-07-03 13:39 UTC by Big-Cake-jpg

就靠一个Windows Server 2019+远程桌面+Visual Studio 2019+iPhone 6 Plus，我完成了导入存档的教程

2021-07-08 08:33 UTC, LTCatt requested changes

2021-07-08 08:33 UTC, LTCatt commented on Minecraft/CurseForge 整合包安装.json
> +	"Description": "���� CurseForge ��ϰ�װ",
**WHAT THE HELL？**

2021-07-08 08:33 UTC, LTCatt commented on Minecraft/CurseForge 整合包安装.json
> +	"Description": "���� CurseForge ��ϰ�װ",
请先重新检查你的文件编码，要求 UTF-8。

2021-07-08 08:54 UTC, Big-Cake-jpg commented on Minecraft/CurseForge 整合包安装.json
> +	"Description": "���� CurseForge ��ϰ�װ",
修好了：）

2021-07-13 09:41 UTC, LTCatt requested changes

2021-07-13 09:41 UTC, LTCatt commented on Minecraft/存档导入.xaml
> +                    Text="当你得到了一个外部存档，却发现不知道怎么导入，该教程可能会成为你的“救命稻草”。请遵循下列步骤来导入你的存档："/>
不要包含非客观、情感化的描述，直说内容即可

2021-07-13 09:41 UTC, LTCatt commented on Minecraft/CurseForge 整合包安装.xaml
> +                    Text="一部分 Minecraft 玩家制作了许许多多的整合包，但是部分新手玩家却不会安装整合包。本教程将告诉你如何安装 CurseForge 整合包。"/>
不要包含非客观、情感化的描述，直说内容即可

2021-07-13 09:41 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +                    Text="2. 选择适合的 Fabric 版本以及 Fabric API"/>
若以 Fabric 为例，请修改帮助标题，表明这只是 Fabric Mod 的教程；Forge 应该另外写一篇。它们俩的不同之处还是不少的

2021-07-13 11:40 UTC, Big-Cake-jpg commented on Minecraft/安装 Mod.xaml
> +                    Text="2. 选择适合的 Fabric 版本以及 Fabric API"/>
> 若以 Fabric 为例，请修改帮助标题，表明这只是 Fabric Mod 的教程；Forge 应该另外写一篇。它们俩的不同之处还是不少的

修好了；）

2021-07-13 12:46 UTC, WTP016-CN commented
对不起……整合包安装撞车了=w=
(只是没看见 现在删掉了

2021-07-13 13:01 UTC, Big-Cake-jpg commented
> 对不起……整合包安装撞车了=w=
> (只是没看见 现在删掉了
> 等你Pull Request好了之后再帮你改吧= =

没事，我的也不完善。如果你的比我的更加完善，我可以撤掉提交

2021-07-15 01:51 UTC, LTCatt requested changes

2021-07-15 01:51 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +        <local:MyHint Margin="0,0,0,15" Text="部分 Mod 需要其它 Mod 作为依赖，在下载安装 Mod 时需要将其一同下载， PCL2 会检查 Mod 是否需要依赖 Mod 。如果有，就会在该 Mod 的下载页置顶显示依赖 Mod" />
尽量少使用提示条……

2021-07-15 01:51 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +<local:MyCard Title="下载并安装 Forge Mod" Margin="0,0,0,15">
Forge/Fabric 的 Mod 安装过程一致，不需要分开写。

2021-07-15 01:51 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +        <local:MyHint Margin="0,0,0,15" Text="Fabric API 是 Fabric 所必须的，如果没有 Fabric API 会导致 Minecraft 无法启动"/>
不会导致 MC 无法启动，只是装的 Mod 用不了吧……

2021-07-15 01:51 UTC, LTCatt commented on Minecraft/CurseForge 整合包安装.xaml
> +                    Text="在 CurseForge 中有各种各样的整合包（ Modpack ），但是很多新手不会安装整合包。这篇帮助就可以让你学会安装整合包"/>
我的意思是，这一段都可以删了……它们不是教程。

2021-07-15 01:51 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +    </StackPanel>
需要补充一段如何通过想安装的 Mod 选择 Forge/Fabric 的内容

2021-07-15 02:03 UTC, Big-Cake-jpg commented on Minecraft/安装 Mod.xaml
> +        <local:MyHint Margin="0,0,0,15" Text="Fabric API 是 Fabric 所必须的，如果没有 Fabric API 会导致 Minecraft 无法启动"/>
> 不会导致 MC 无法启动，只是装的 Mod 用不了吧……

没有Fabric API会使得游戏无法启动，显示Fabric特有的Couldn't Launch

2021-07-15 02:03 UTC, Big-Cake-jpg commented on Minecraft/安装 Mod.xaml
> +        <local:MyHint Margin="0,0,0,15" Text="Fabric API 是 Fabric 所必须的，如果没有 Fabric API 会导致 Minecraft 无法启动"/>
> > 不会导致 MC 无法启动，只是装的 Mod 用不了吧……
> 
> 没有Fabric API会使得游戏无法启动，显示Fabric特有的Couldn't Launch

除了部分模组

2021-07-15 08:09 UTC, LTCatt reviewed
还有两条没解决

2021-07-16 01:57 UTC, LTCatt approved these changes

2021-07-16 01:57 UTC, merged

2021-07-20 09:12 UTC, LTCatt commented
抱歉，关于 “存档导入” 页面，在我复查的时候由于内容质量较低，我暂时删掉了……
你可以再丢一个 PR，我会在 Review 的时候标注修改建议……

2021-07-20 13:06 UTC, Big-Cake-jpg commented
没事
弱弱的问一句，活跃橙奖励还会有嘛qwq
---原始邮件---
***@***.***&gt;
发送时间:2021年7月20日 星期二 下午5:12
***@***.***&gt;
***@***.******@***.***&gt;
主题:Re: [LTCatt/PCL2Help] 增加一部分教程 (#52)



抱歉，关于&nbsp;“存档导入”&nbsp;页面，在我复查的时候由于内容质量较低，我暂时删掉了……
你可以再丢一个&nbsp;PR，我会在&nbsp;Review&nbsp;的时候标注修改建议……

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

2021-07-21 09:58 UTC, LTCatt commented
详见 https://shimo.im/docs/qKPttVvXKqPD8YDC