增加 整合包安装 教程
LTCatt/PCL2Help pull request #55
Opened 2021-07-16 02:04 UTC by WTP016-CN

删除 CurseForge 整合包安装 教程
增加 整合包安装 教程

2021-07-19 08:10 UTC, LTCatt requested changes

2021-07-19 08:10 UTC, LTCatt commented on Minecraft/整合包安装.xaml
> +                       Text="3. 在帖子中找到下载链接，点击，点击”请点击此链接“，打开 XPlus 下载链接，选择 OneIndex，打开”PCL版本\Fabric版本\1.17.1，选择最新的版本，下载并解压缩，打开 PCL2 启动器，点击启动，您即可进入游戏。" HorizontalAlignment="Left"/>
建议直接快进到下载好了一个压缩包，也不要限定在 MCBBS，这样适用性更大

2021-07-19 13:50 UTC, WTP016-CN commented
改好了 =-=

2021-07-20 08:12 UTC, LTCatt requested changes

2021-07-20 08:12 UTC, LTCatt commented on Minecraft/整合包安装.xaml
> +                       Text="解压缩此压缩文件(即结尾为 .zip / .rar 的文件)，找到启动器，登录 Mojang / Microsoft 账号，启动游戏，您即可游玩游戏。" HorizontalAlignment="Left"/>
umm 其实这个也分两种情况。
一种是你写的直接压缩游戏，一种是 MCBBS/HMCL/MMC 格式的整合包，还是需要在 PCL 里安装

2021-07-20 09:38 UTC, WTP016-CN commented
改好了 但是我这里不知道为什么显示不出来 Coding 的图像 下次还是用 jsdelivr(

2021-07-20 09:50 UTC, LTCatt commented on Minecraft/整合包安装.xaml
> +<local:MyCard Title="对于结尾为 .zip / .rar 的压缩文件整合包" Margin="0,0,0,15" CanSwap="True" IsSwaped="True">
MCBBS 或 HMCL / MultiMC(MMC) 格式的整合包结尾同样为 .zip，不能通过这个方式辨别。我想想……要不然干脆我让 PCL2 也支持压缩包形式的游戏作为整合包安装得了，之后你再改改这个吧（

2021-07-20 09:57 UTC, WTP016-CN commented on Minecraft/整合包安装.xaml
> +<local:MyCard Title="对于结尾为 .zip / .rar 的压缩文件整合包" Margin="0,0,0,15" CanSwap="True" IsSwaped="True">
好吧=-=

2021-07-20 09:58 UTC, WTP016-CN commented on Minecraft/整合包安装.xaml
> +<local:MyCard Title="对于结尾为 .zip / .rar 的压缩文件整合包" Margin="0,0,0,15" CanSwap="True" IsSwaped="True">
我先把这一段改好 PCL2什么时候改好再 Merge 吧= =

2021-07-21 08:09 UTC, LTCatt approved these changes
将在 PCL2 更新游戏压缩包作为整合包安装后被合并

2021-08-05 14:40 UTC, LTCatt commented
处理一下冲突……
PCL2 下一个版本会支持将游戏文件夹压缩包作为游戏整合包导入，所以可以一并修改一下文件。

2021-08-05 14:50 UTC, WTP016-CN commented
> 处理一下冲突……
> PCL2 下一个版本会支持将游戏文件夹压缩包作为游戏整合包导入，所以可以一并修改一下文件。

改好了
但是因为我这里删除了 CurseForge 整合包安装 教程
所以需要龙猫删除掉 CurseForge 整合包安装教程后才能合并= =

2021-08-05 15:50 UTC, merged