修改 数据包安装、整合包安装、Mod安装教程
LTCatt/PCL2Help pull request #75
Opened 2021-08-20 03:08 UTC by WTP016-CN

修改如下:
* 删除 Mod 安装教程内的按 Fabric 标签搜索 Mod
* 在整合包安装教程内增加来自 FTB Wiki 的整合包相关介绍及下载渠道
* 修改数据包安装教程 增加数据包科普 下载渠道(MCBBS链接指向暂时无法解决 "&" 在xaml文件内冲突但MCBBS源链接含有&) 修改部分言辞 修改此教程的 JSON 的 keyword

2021-08-21 12:41 UTC, LTCatt requested changes

2021-08-21 12:41 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +        <TextBlock TextWrapping="Wrap" Margin="0,0,0,4" LineHeight="17" Text="你可以通过以下的按钮打开 MCBBS Mod 分享板块。" />
无需类似冗余介绍。

2021-08-21 12:41 UTC, LTCatt commented on Minecraft/安装 Mod.xaml
> +        <TextBlock TextWrapping="Wrap" Margin="0,0,0,4" LineHeight="17" Text="在 PCL2 主页点击&quot;版本选择&quot;按钮，找到您需要安装 Mod 的版本，点击右侧的齿轮，点击&quot;打开版本文件夹&quot;按钮。"/>
PCL2 的版本设置中有 Mod 管理一项，可以直接打开 mods 文件夹。

2021-08-21 12:41 UTC, LTCatt commented on Minecraft/数据包安装.xaml
> +                   Text="打开 MCBBS 光影板块" EventType="打开网页" EventData="https://www.mcbbs.net/forum.php?mod=forumdisplay&amp;fid=39&amp;filter=typeid&amp;typeid=146" />
光影？

2021-08-21 12:41 UTC, LTCatt commented on 帮助/提交帮助 - Git.xaml
> +        <local:MyHint Margin="0,15,0,0" Text="注意，在请求合并之前请先请确保你的仓库分支与原仓库是同步的，GitHub 不会自动同步你的分支仓库，请在 Pull Request 前进入你的 Fork 仓库界面，点击 ”Fetch upstream”，再点击“Fetch and merge” 以同步上游仓库。" />
点击 ”Fetch upstream”，

左引号反了

2021-08-21 12:41 UTC, LTCatt commented on 指南/整合包制作 - Public.xaml
> +                   Text="你可以在 设置 → 个性化 → 主页 中自定义启动器的主页。&#xa;你也可以将你的主页 XAML 文件上传到服务器，并通过 “联网更新” 选项实现主页的动态更新。" />
各个表示步骤的箭头旁边无需加入空格，以使左右步骤从视觉上连续

2021-08-21 12:50 UTC, WTP016-CN commented
解决完了这一大堆乱七八糟的问题- -

2021-08-23 08:48 UTC, LTCatt requested changes

2021-08-23 08:48 UTC, LTCatt commented on 指南/整合包制作 - Public.xaml
> +                   Text="你可以在 设置→ 个性化→功能隐藏 中关闭你不需要的功能入口，例如下载、个性化设置等页面。" />
……没删干净

2021-08-23 08:48 UTC, LTCatt commented on 帮助/自定义帮助 - JSON 格式.xaml
> +                   Text="帮助条目分为两类，第一类在点击后会在 PCL2 中打开一个新的帮助子页面，第二类则会触发事件（通常用于打开网页或执行程序），第三类会弹出弹窗。&#xa;下列两项分别为第一类、第二类和第三类帮助条目的示例。" />
“第三类” 实际上也属于第二类，只是 Type 是弹窗，因此无需分开说。

2021-08-23 15:58 UTC, LTCatt requested changes

2021-08-23 15:58 UTC, LTCatt commented on 个性化/XAML 格式.xaml
> +
按钮教学 1 里已经补充了弹窗了 =。=
不需要这段……回滚了就行（

2021-08-24 01:06 UTC, LiuXuan-bk commented on Minecraft/安装 Mod.xaml
> -        <local:MyHint Margin="0,0,0,15" Text="如果你想快速查找支持 Fabric 加载器的 Mod，不妨试试在“标签”下选择“Fabric”。" IsWarn="False" />
目前标签中没有Fabric选项

2021-08-24 02:38 UTC, WTP016-CN commented on Minecraft/安装 Mod.xaml
> -        <local:MyHint Margin="0,0,0,15" Text="如果你想快速查找支持 Fabric 加载器的 Mod，不妨试试在“标签”下选择“Fabric”。" IsWarn="False" />
红色代表删除

2021-08-28 15:15 UTC, LTCatt approved these changes

2021-08-28 15:15 UTC, merged