原来的图床有时候加载，有时候无法加载，修复图传问题
LTCatt/PCL2Help pull request #80
Opened 2021-08-23 10:39 UTC by Dongyifengs

2021-08-23 10:45 UTC, Dongyifengs reviewed
原来的图传加载出现了问题，更换图床

2021-08-23 10:50 UTC, WTP016-CN commented
像这样图片加载的更改不应加入作者名单

2021-08-23 12:13 UTC, WTP016-CN requested changes

2021-08-23 12:13 UTC, WTP016-CN commented on Minecraft/设置分配内存大小.xaml
> +    <local:MyHint Margin="0,-5,0,15" Text="请注意，错误的内存分配会造成游戏不稳定甚至不正常的内存溢出。&#xa;请在自行修改内存前务必谨慎操作！若没有特殊需要，请谨慎修改"/>
前文已经说了谨慎操作了- -

2021-08-23 12:13 UTC, WTP016-CN commented on Minecraft/设置分配内存大小.xaml
> +                   Text="1.打开您的 PCL 2 启动器，在主页点击左下方的“版本选择”按钮。" />
注意 根据以前的 Pull Request 龙猫建议在 . 与正文之间加一个空格

2021-08-23 12:13 UTC, WTP016-CN commented on Minecraft/设置分配内存大小.xaml
> +<local:MyCard Title="2. 针对启动器所有游戏内存进行调整">
没必要所有都加这个备注 加载错了

2021-08-23 12:13 UTC, WTP016-CN commented on 指南/整合包制作 - Public.xaml
> +                   Text="你可以将你做的 Custom.xaml，文件上传到你的GitHub，创建一个仓库，将 Custom.xaml 文件放置该仓库。使用https://cdn.jsdelivr.net/gh/你Github的名称/你Github前面创建的仓库名称@仓库版本号/Custom.xaml" />
Github 前后空格 jsdelivr CDN 格式:
https://cdn.jsdelivr.net/gh/Github 用户名/Github 仓库@分支/Custom.xaml

2021-08-23 12:13 UTC, WTP016-CN commented on 指南/整合包制作 - Public.xaml
> +                   Text="然后在PCL2 → 设置 → 个性化 → 自定义主页   找到联网更新 如下图所示 " />
这里找到联网更新差太多了

2021-08-23 16:02 UTC, LTCatt requested changes
WTP 说的那部分也得改 =。=

2021-08-23 16:02 UTC, LTCatt commented on 指南/整合包制作 - Public.xaml
> +                   Text="你可以将你做的 Custom.xaml，文件上传到你的GitHub，创建一个仓库，将 Custom.xaml 文件放置该仓库。使用https://cdn.jsdelivr.net/gh/你Github的名称/你Github前面创建的仓库名称@仓库版本号/Custom.xaml" />
强烈不建议在这里推荐 GitHub 用作联网主页加载，GitHub 在国内直连情况很差很差。建议删除。

2021-08-23 17:13 UTC, WTP016-CN commented on 指南/整合包制作 - Public.xaml
> +                   Text="你可以将你做的 Custom.xaml，文件上传到你的GitHub，创建一个仓库，将 Custom.xaml 文件放置该仓库。使用https://cdn.jsdelivr.net/gh/你Github的名称/你Github前面创建的仓库名称@仓库版本号/Custom.xaml" />
这里建议使用 Coding 或者码云等其他国内平台

2021-08-23 22:55 UTC, Dongyifengs commented
设置分配内存大小 中，部分图传无法正常加载，修改图床，正常加载全局分配内存的图床

2021-08-24 02:31 UTC, WTP016-CN requested changes

2021-08-24 02:31 UTC, WTP016-CN commented on Minecraft/设置分配内存大小.xaml
> +                   Text="4. 滑动至下方，找到“游戏内存”选项卡，选择“自定义”，然后滑动圆点即可手动调整。&#xa;    此时，该版本的启动内存已为固定值，不再自动变更。" />
无需空格 &#xa;后直接跟内容即可

2021-08-24 06:44 UTC, Dongyifengs commented
可以先上传 设置分配内存大小 了
B🐱‍🏍✨

2021-08-24 06:48 UTC, WTP016-CN commented
> 可以先上传 设置分配内存大小 了
> B🐱‍🏍✨

Github是不能分开PR的（

2021-08-24 07:10 UTC, Dongyifengs reviewed
> > 可以先上传设置内存大小了
> > B🐱‍🏍✨
> 
> Github是不能单独PR的（

我重新搞一遍

2021-08-24 07:10 UTC, closed without merging