图床修改
LTCatt/PCL2Help pull request #88
Opened 2021-08-24 07:59 UTC by Dongyifengs

2021-08-24 12:00 UTC, Dongyifengs commented
目前发现发开PCL2 文件发无法使用，稍后修改再次提交

2021-08-25 03:14 UTC, WTP016-CN requested changes

2021-08-25 03:14 UTC, WTP016-CN commented on 帮助/提交帮助 - VSCode.xaml
> +        </local:MyCard>
此处前文已经有提及,无需重复

2021-08-25 03:14 UTC, WTP016-CN commented on 帮助/提交帮助 - VSCode.xaml
> +                Text="9. 点击坐下角的 “回收” 图标，登录你的Github的账号，即可完成上传"/>
建议先别改这个 VSCode 我的修改中包含了 VSCode 上传代码的教程 先还原这个吧- -

2021-08-25 03:14 UTC, WTP016-CN commented on 帮助/提交帮助 - VSCode.xaml
> +                Text="12. 点击 View Pull Request 即可上传至 Pull Reques 待管理员审核通过，即可正式上传至PCL2 Help 帮助库"/>
Pull Request

2021-08-25 03:14 UTC, WTP016-CN commented on 帮助/提交帮助 - VSCode.xaml
> +                Text="12. 点击 View Pull Request 即可上传至 Pull Reques 待管理员审核通过，即可正式上传至PCL2 Help 帮助库"/>
PCL2 与前文需要一个空格以分开 不需要添加 Help 直接写帮助库即可

2021-08-25 03:14 UTC, WTP016-CN commented on README.md
> +请打开 PCL2，依次进入 “`更多` → `帮助库` → `启动器` → `参与完善 PCL2 帮助库`”，该帮助文档中有详细的参与流程。
不需要加入``

2021-08-25 03:14 UTC, WTP016-CN commented on README.md
> +当然，帮助库建立初期，内容较为空缺，非常需要你们的参与！
看到这个的是一个人而不是一坨人

2021-08-25 03:14 UTC, WTP016-CN commented on README.md
> +有许多 MC 新人在游戏过程中会遇到很多疑惑，也有 PCL2 用户在使用时出现了一些问题。本帮助库的目标即为尽量帮助大家解决这些问题，让新人对 MC 更为熟悉,快速了解 PCL2 以及 Minecraft。
前文提到熟悉 MC 无需重复 了解 Minecraft

2021-08-25 03:14 UTC, WTP016-CN commented on Minecraft/设置分配内存大小.xaml
> +<local:MyHint Margin="0,0,0,15" Text="作者：一闪，DreamUniverse、Dong_Yi_feng" IsWarn="False" />
非大段更改不能加入作者

2021-08-25 03:14 UTC, WTP016-CN commented on Minecraft/设置分配内存大小.json
> +    "__Author__": "一闪、DreamUniverse、Dong_Yi_feng",
非大段修改不能加入作者

2021-08-25 03:30 UTC, closed without merging

2021-08-25 03:41 UTC, Dongyifengs commented on Minecraft/设置分配内存大小.json
> +    "__Author__": "一闪、DreamUniverse、Dong_Yi_feng",
https://github.com/LTCatt/PCL2Help/pull/90
重新上传，已删除

2021-08-25 03:41 UTC, Dongyifengs commented on Minecraft/设置分配内存大小.xaml
> +<local:MyHint Margin="0,0,0,15" Text="作者：一闪，DreamUniverse、Dong_Yi_feng" IsWarn="False" />
https://github.com/LTCatt/PCL2Help/pull/90
重新上传，已删除

2021-08-25 03:41 UTC, Dongyifengs commented on README.md
> +有许多 MC 新人在游戏过程中会遇到很多疑惑，也有 PCL2 用户在使用时出现了一些问题。本帮助库的目标即为尽量帮助大家解决这些问题，让新人对 MC 更为熟悉,快速了解 PCL2 以及 Minecraft。
已删除

2021-08-25 03:41 UTC, Dongyifengs commented on README.md
> +当然，帮助库建立初期，内容较为空缺，非常需要你们的参与！
已删除

2021-08-25 03:41 UTC, Dongyifengs commented on README.md
> +请打开 PCL2，依次进入 “`更多` → `帮助库` → `启动器` → `参与完善 PCL2 帮助库`”，该帮助文档中有详细的参与流程。
已删除

2021-08-25 03:41 UTC, Dongyifengs commented on 帮助/提交帮助 - VSCode.xaml
> +        </local:MyCard>
尝试修改

2021-08-25 03:41 UTC, Dongyifengs commented on 帮助/提交帮助 - VSCode.xaml
> +                Text="9. 点击坐下角的 “回收” 图标，登录你的Github的账号，即可完成上传"/>
已删除

2021-08-25 03:41 UTC, Dongyifengs commented on 帮助/提交帮助 - VSCode.xaml
> +                Text="9. 点击坐下角的 “回收” 图标，登录你的Github的账号，即可完成上传"/>
我这个也有呀